/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.91
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PushParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PushParams{}

// PushParams struct for PushParams
type PushParams struct {
	ProjectId            string          `json:"projectId"`
	SecretManagerId      *string         `json:"secretManagerId,omitempty"`
	CodeUrl              string          `json:"codeUrl"`
	CodeEntryFile        string          `json:"codeEntryFile"`
	GenericBaseImageType *string         `json:"genericBaseImageType,omitempty"`
	VersionName          string          `json:"versionName"`
	BranchName           *string         `json:"branchName,omitempty"`
	OverwriteVersionId   *string         `json:"overwriteVersionId,omitempty"`
	Model                ImportModelInfo `json:"model"`
	AdditionalProperties map[string]interface{}
}

type _PushParams PushParams

// NewPushParams instantiates a new PushParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPushParams(projectId string, codeUrl string, codeEntryFile string, versionName string, model ImportModelInfo) *PushParams {
	this := PushParams{}
	this.ProjectId = projectId
	this.CodeUrl = codeUrl
	this.CodeEntryFile = codeEntryFile
	this.VersionName = versionName
	this.Model = model
	return &this
}

// NewPushParamsWithDefaults instantiates a new PushParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPushParamsWithDefaults() *PushParams {
	this := PushParams{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *PushParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *PushParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *PushParams) SetProjectId(v string) {
	o.ProjectId = v
}

// GetSecretManagerId returns the SecretManagerId field value if set, zero value otherwise.
func (o *PushParams) GetSecretManagerId() string {
	if o == nil || IsNil(o.SecretManagerId) {
		var ret string
		return ret
	}
	return *o.SecretManagerId
}

// GetSecretManagerIdOk returns a tuple with the SecretManagerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushParams) GetSecretManagerIdOk() (*string, bool) {
	if o == nil || IsNil(o.SecretManagerId) {
		return nil, false
	}
	return o.SecretManagerId, true
}

// HasSecretManagerId returns a boolean if a field has been set.
func (o *PushParams) HasSecretManagerId() bool {
	if o != nil && !IsNil(o.SecretManagerId) {
		return true
	}

	return false
}

// SetSecretManagerId gets a reference to the given string and assigns it to the SecretManagerId field.
func (o *PushParams) SetSecretManagerId(v string) {
	o.SecretManagerId = &v
}

// GetCodeUrl returns the CodeUrl field value
func (o *PushParams) GetCodeUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodeUrl
}

// GetCodeUrlOk returns a tuple with the CodeUrl field value
// and a boolean to check if the value has been set.
func (o *PushParams) GetCodeUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeUrl, true
}

// SetCodeUrl sets field value
func (o *PushParams) SetCodeUrl(v string) {
	o.CodeUrl = v
}

// GetCodeEntryFile returns the CodeEntryFile field value
func (o *PushParams) GetCodeEntryFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodeEntryFile
}

// GetCodeEntryFileOk returns a tuple with the CodeEntryFile field value
// and a boolean to check if the value has been set.
func (o *PushParams) GetCodeEntryFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeEntryFile, true
}

// SetCodeEntryFile sets field value
func (o *PushParams) SetCodeEntryFile(v string) {
	o.CodeEntryFile = v
}

// GetGenericBaseImageType returns the GenericBaseImageType field value if set, zero value otherwise.
func (o *PushParams) GetGenericBaseImageType() string {
	if o == nil || IsNil(o.GenericBaseImageType) {
		var ret string
		return ret
	}
	return *o.GenericBaseImageType
}

// GetGenericBaseImageTypeOk returns a tuple with the GenericBaseImageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushParams) GetGenericBaseImageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.GenericBaseImageType) {
		return nil, false
	}
	return o.GenericBaseImageType, true
}

// HasGenericBaseImageType returns a boolean if a field has been set.
func (o *PushParams) HasGenericBaseImageType() bool {
	if o != nil && !IsNil(o.GenericBaseImageType) {
		return true
	}

	return false
}

// SetGenericBaseImageType gets a reference to the given string and assigns it to the GenericBaseImageType field.
func (o *PushParams) SetGenericBaseImageType(v string) {
	o.GenericBaseImageType = &v
}

// GetVersionName returns the VersionName field value
func (o *PushParams) GetVersionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionName
}

// GetVersionNameOk returns a tuple with the VersionName field value
// and a boolean to check if the value has been set.
func (o *PushParams) GetVersionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionName, true
}

// SetVersionName sets field value
func (o *PushParams) SetVersionName(v string) {
	o.VersionName = v
}

// GetBranchName returns the BranchName field value if set, zero value otherwise.
func (o *PushParams) GetBranchName() string {
	if o == nil || IsNil(o.BranchName) {
		var ret string
		return ret
	}
	return *o.BranchName
}

// GetBranchNameOk returns a tuple with the BranchName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushParams) GetBranchNameOk() (*string, bool) {
	if o == nil || IsNil(o.BranchName) {
		return nil, false
	}
	return o.BranchName, true
}

// HasBranchName returns a boolean if a field has been set.
func (o *PushParams) HasBranchName() bool {
	if o != nil && !IsNil(o.BranchName) {
		return true
	}

	return false
}

// SetBranchName gets a reference to the given string and assigns it to the BranchName field.
func (o *PushParams) SetBranchName(v string) {
	o.BranchName = &v
}

// GetOverwriteVersionId returns the OverwriteVersionId field value if set, zero value otherwise.
func (o *PushParams) GetOverwriteVersionId() string {
	if o == nil || IsNil(o.OverwriteVersionId) {
		var ret string
		return ret
	}
	return *o.OverwriteVersionId
}

// GetOverwriteVersionIdOk returns a tuple with the OverwriteVersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushParams) GetOverwriteVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.OverwriteVersionId) {
		return nil, false
	}
	return o.OverwriteVersionId, true
}

// HasOverwriteVersionId returns a boolean if a field has been set.
func (o *PushParams) HasOverwriteVersionId() bool {
	if o != nil && !IsNil(o.OverwriteVersionId) {
		return true
	}

	return false
}

// SetOverwriteVersionId gets a reference to the given string and assigns it to the OverwriteVersionId field.
func (o *PushParams) SetOverwriteVersionId(v string) {
	o.OverwriteVersionId = &v
}

// GetModel returns the Model field value
func (o *PushParams) GetModel() ImportModelInfo {
	if o == nil {
		var ret ImportModelInfo
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *PushParams) GetModelOk() (*ImportModelInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *PushParams) SetModel(v ImportModelInfo) {
	o.Model = v
}

func (o PushParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PushParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	if !IsNil(o.SecretManagerId) {
		toSerialize["secretManagerId"] = o.SecretManagerId
	}
	toSerialize["codeUrl"] = o.CodeUrl
	toSerialize["codeEntryFile"] = o.CodeEntryFile
	if !IsNil(o.GenericBaseImageType) {
		toSerialize["genericBaseImageType"] = o.GenericBaseImageType
	}
	toSerialize["versionName"] = o.VersionName
	if !IsNil(o.BranchName) {
		toSerialize["branchName"] = o.BranchName
	}
	if !IsNil(o.OverwriteVersionId) {
		toSerialize["overwriteVersionId"] = o.OverwriteVersionId
	}
	toSerialize["model"] = o.Model

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PushParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectId",
		"codeUrl",
		"codeEntryFile",
		"versionName",
		"model",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPushParams := _PushParams{}

	err = json.Unmarshal(data, &varPushParams)

	if err != nil {
		return err
	}

	*o = PushParams(varPushParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "projectId")
		delete(additionalProperties, "secretManagerId")
		delete(additionalProperties, "codeUrl")
		delete(additionalProperties, "codeEntryFile")
		delete(additionalProperties, "genericBaseImageType")
		delete(additionalProperties, "versionName")
		delete(additionalProperties, "branchName")
		delete(additionalProperties, "overwriteVersionId")
		delete(additionalProperties, "model")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePushParams struct {
	value *PushParams
	isSet bool
}

func (v NullablePushParams) Get() *PushParams {
	return v.value
}

func (v *NullablePushParams) Set(val *PushParams) {
	v.value = val
	v.isSet = true
}

func (v NullablePushParams) IsSet() bool {
	return v.isSet
}

func (v *NullablePushParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePushParams(val *PushParams) *NullablePushParams {
	return &NullablePushParams{value: val, isSet: true}
}

func (v NullablePushParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePushParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
