/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.100
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetContainerLabelsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetContainerLabelsResponse{}

// GetContainerLabelsResponse struct for GetContainerLabelsResponse
type GetContainerLabelsResponse struct {
	// Construct a type with a set of properties K of type T
	Labels               map[string]interface{} `json:"labels"`
	AdditionalProperties map[string]interface{}
}

type _GetContainerLabelsResponse GetContainerLabelsResponse

// NewGetContainerLabelsResponse instantiates a new GetContainerLabelsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContainerLabelsResponse(labels map[string]interface{}) *GetContainerLabelsResponse {
	this := GetContainerLabelsResponse{}
	this.Labels = labels
	return &this
}

// NewGetContainerLabelsResponseWithDefaults instantiates a new GetContainerLabelsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContainerLabelsResponseWithDefaults() *GetContainerLabelsResponse {
	this := GetContainerLabelsResponse{}
	return &this
}

// GetLabels returns the Labels field value
func (o *GetContainerLabelsResponse) GetLabels() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *GetContainerLabelsResponse) GetLabelsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *GetContainerLabelsResponse) SetLabels(v map[string]interface{}) {
	o.Labels = v
}

func (o GetContainerLabelsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetContainerLabelsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["labels"] = o.Labels

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetContainerLabelsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetContainerLabelsResponse := _GetContainerLabelsResponse{}

	err = json.Unmarshal(data, &varGetContainerLabelsResponse)

	if err != nil {
		return err
	}

	*o = GetContainerLabelsResponse(varGetContainerLabelsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetContainerLabelsResponse struct {
	value *GetContainerLabelsResponse
	isSet bool
}

func (v NullableGetContainerLabelsResponse) Get() *GetContainerLabelsResponse {
	return v.value
}

func (v *NullableGetContainerLabelsResponse) Set(val *GetContainerLabelsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContainerLabelsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContainerLabelsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContainerLabelsResponse(val *GetContainerLabelsResponse) *NullableGetContainerLabelsResponse {
	return &NullableGetContainerLabelsResponse{value: val, isSet: true}
}

func (v NullableGetContainerLabelsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContainerLabelsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
