/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.683
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GenerateLabelParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateLabelParams{}

// GenerateLabelParams struct for GenerateLabelParams
type GenerateLabelParams struct {
	ProjectId            string     `json:"projectId"`
	SessionRunId         string     `json:"sessionRunId"`
	Epoch                float64    `json:"epoch"`
	NumOfSamplesToLabel  *float64   `json:"numOfSamplesToLabel,omitempty"`
	Filters              []ESFilter `json:"filters,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GenerateLabelParams GenerateLabelParams

// NewGenerateLabelParams instantiates a new GenerateLabelParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateLabelParams(projectId string, sessionRunId string, epoch float64) *GenerateLabelParams {
	this := GenerateLabelParams{}
	this.ProjectId = projectId
	this.SessionRunId = sessionRunId
	this.Epoch = epoch
	return &this
}

// NewGenerateLabelParamsWithDefaults instantiates a new GenerateLabelParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateLabelParamsWithDefaults() *GenerateLabelParams {
	this := GenerateLabelParams{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *GenerateLabelParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GenerateLabelParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GenerateLabelParams) SetProjectId(v string) {
	o.ProjectId = v
}

// GetSessionRunId returns the SessionRunId field value
func (o *GenerateLabelParams) GetSessionRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionRunId
}

// GetSessionRunIdOk returns a tuple with the SessionRunId field value
// and a boolean to check if the value has been set.
func (o *GenerateLabelParams) GetSessionRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionRunId, true
}

// SetSessionRunId sets field value
func (o *GenerateLabelParams) SetSessionRunId(v string) {
	o.SessionRunId = v
}

// GetEpoch returns the Epoch field value
func (o *GenerateLabelParams) GetEpoch() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Epoch
}

// GetEpochOk returns a tuple with the Epoch field value
// and a boolean to check if the value has been set.
func (o *GenerateLabelParams) GetEpochOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Epoch, true
}

// SetEpoch sets field value
func (o *GenerateLabelParams) SetEpoch(v float64) {
	o.Epoch = v
}

// GetNumOfSamplesToLabel returns the NumOfSamplesToLabel field value if set, zero value otherwise.
func (o *GenerateLabelParams) GetNumOfSamplesToLabel() float64 {
	if o == nil || IsNil(o.NumOfSamplesToLabel) {
		var ret float64
		return ret
	}
	return *o.NumOfSamplesToLabel
}

// GetNumOfSamplesToLabelOk returns a tuple with the NumOfSamplesToLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateLabelParams) GetNumOfSamplesToLabelOk() (*float64, bool) {
	if o == nil || IsNil(o.NumOfSamplesToLabel) {
		return nil, false
	}
	return o.NumOfSamplesToLabel, true
}

// HasNumOfSamplesToLabel returns a boolean if a field has been set.
func (o *GenerateLabelParams) HasNumOfSamplesToLabel() bool {
	if o != nil && !IsNil(o.NumOfSamplesToLabel) {
		return true
	}

	return false
}

// SetNumOfSamplesToLabel gets a reference to the given float64 and assigns it to the NumOfSamplesToLabel field.
func (o *GenerateLabelParams) SetNumOfSamplesToLabel(v float64) {
	o.NumOfSamplesToLabel = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *GenerateLabelParams) GetFilters() []ESFilter {
	if o == nil || IsNil(o.Filters) {
		var ret []ESFilter
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateLabelParams) GetFiltersOk() ([]ESFilter, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *GenerateLabelParams) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []ESFilter and assigns it to the Filters field.
func (o *GenerateLabelParams) SetFilters(v []ESFilter) {
	o.Filters = v
}

func (o GenerateLabelParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateLabelParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	toSerialize["sessionRunId"] = o.SessionRunId
	toSerialize["epoch"] = o.Epoch
	if !IsNil(o.NumOfSamplesToLabel) {
		toSerialize["numOfSamplesToLabel"] = o.NumOfSamplesToLabel
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GenerateLabelParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectId",
		"sessionRunId",
		"epoch",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenerateLabelParams := _GenerateLabelParams{}

	err = json.Unmarshal(data, &varGenerateLabelParams)

	if err != nil {
		return err
	}

	*o = GenerateLabelParams(varGenerateLabelParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "projectId")
		delete(additionalProperties, "sessionRunId")
		delete(additionalProperties, "epoch")
		delete(additionalProperties, "numOfSamplesToLabel")
		delete(additionalProperties, "filters")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGenerateLabelParams struct {
	value *GenerateLabelParams
	isSet bool
}

func (v NullableGenerateLabelParams) Get() *GenerateLabelParams {
	return v.value
}

func (v *NullableGenerateLabelParams) Set(val *GenerateLabelParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateLabelParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateLabelParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateLabelParams(val *GenerateLabelParams) *NullableGenerateLabelParams {
	return &NullableGenerateLabelParams{value: val, isSet: true}
}

func (v NullableGenerateLabelParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateLabelParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
