/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.688
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SetCodeChallengeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetCodeChallengeRequest{}

// SetCodeChallengeRequest struct for SetCodeChallengeRequest
type SetCodeChallengeRequest struct {
	CodeChallenge        string `json:"codeChallenge"`
	AdditionalProperties map[string]interface{}
}

type _SetCodeChallengeRequest SetCodeChallengeRequest

// NewSetCodeChallengeRequest instantiates a new SetCodeChallengeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetCodeChallengeRequest(codeChallenge string) *SetCodeChallengeRequest {
	this := SetCodeChallengeRequest{}
	this.CodeChallenge = codeChallenge
	return &this
}

// NewSetCodeChallengeRequestWithDefaults instantiates a new SetCodeChallengeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetCodeChallengeRequestWithDefaults() *SetCodeChallengeRequest {
	this := SetCodeChallengeRequest{}
	return &this
}

// GetCodeChallenge returns the CodeChallenge field value
func (o *SetCodeChallengeRequest) GetCodeChallenge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodeChallenge
}

// GetCodeChallengeOk returns a tuple with the CodeChallenge field value
// and a boolean to check if the value has been set.
func (o *SetCodeChallengeRequest) GetCodeChallengeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeChallenge, true
}

// SetCodeChallenge sets field value
func (o *SetCodeChallengeRequest) SetCodeChallenge(v string) {
	o.CodeChallenge = v
}

func (o SetCodeChallengeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetCodeChallengeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["codeChallenge"] = o.CodeChallenge

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetCodeChallengeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"codeChallenge",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetCodeChallengeRequest := _SetCodeChallengeRequest{}

	err = json.Unmarshal(data, &varSetCodeChallengeRequest)

	if err != nil {
		return err
	}

	*o = SetCodeChallengeRequest(varSetCodeChallengeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "codeChallenge")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetCodeChallengeRequest struct {
	value *SetCodeChallengeRequest
	isSet bool
}

func (v NullableSetCodeChallengeRequest) Get() *SetCodeChallengeRequest {
	return v.value
}

func (v *NullableSetCodeChallengeRequest) Set(val *SetCodeChallengeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetCodeChallengeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetCodeChallengeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetCodeChallengeRequest(val *SetCodeChallengeRequest) *NullableSetCodeChallengeRequest {
	return &NullableSetCodeChallengeRequest{value: val, isSet: true}
}

func (v NullableSetCodeChallengeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetCodeChallengeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
