/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetCollectionSamplesMetadataParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCollectionSamplesMetadataParams{}

// GetCollectionSamplesMetadataParams struct for GetCollectionSamplesMetadataParams
type GetCollectionSamplesMetadataParams struct {
	// Active filter spec (same shape used by `getCollectionSampleOrder`). Each field's bucket counts are computed against the other fields' filters, so the sidebar shows the right \"available samples per bucket if you pick this option next\" numbers.
	Filters              []CollectionFilterSpec `json:"filters,omitempty"`
	InferenceArtifactId  string                 `json:"inferenceArtifactId"`
	VersionId            *string                `json:"versionId,omitempty"`
	CollectionId         string                 `json:"collectionId"`
	ProjectId            string                 `json:"projectId"`
	AdditionalProperties map[string]interface{}
}

type _GetCollectionSamplesMetadataParams GetCollectionSamplesMetadataParams

// NewGetCollectionSamplesMetadataParams instantiates a new GetCollectionSamplesMetadataParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCollectionSamplesMetadataParams(inferenceArtifactId string, collectionId string, projectId string) *GetCollectionSamplesMetadataParams {
	this := GetCollectionSamplesMetadataParams{}
	this.InferenceArtifactId = inferenceArtifactId
	this.CollectionId = collectionId
	this.ProjectId = projectId
	return &this
}

// NewGetCollectionSamplesMetadataParamsWithDefaults instantiates a new GetCollectionSamplesMetadataParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCollectionSamplesMetadataParamsWithDefaults() *GetCollectionSamplesMetadataParams {
	this := GetCollectionSamplesMetadataParams{}
	return &this
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *GetCollectionSamplesMetadataParams) GetFilters() []CollectionFilterSpec {
	if o == nil || IsNil(o.Filters) {
		var ret []CollectionFilterSpec
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCollectionSamplesMetadataParams) GetFiltersOk() ([]CollectionFilterSpec, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *GetCollectionSamplesMetadataParams) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []CollectionFilterSpec and assigns it to the Filters field.
func (o *GetCollectionSamplesMetadataParams) SetFilters(v []CollectionFilterSpec) {
	o.Filters = v
}

// GetInferenceArtifactId returns the InferenceArtifactId field value
func (o *GetCollectionSamplesMetadataParams) GetInferenceArtifactId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InferenceArtifactId
}

// GetInferenceArtifactIdOk returns a tuple with the InferenceArtifactId field value
// and a boolean to check if the value has been set.
func (o *GetCollectionSamplesMetadataParams) GetInferenceArtifactIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InferenceArtifactId, true
}

// SetInferenceArtifactId sets field value
func (o *GetCollectionSamplesMetadataParams) SetInferenceArtifactId(v string) {
	o.InferenceArtifactId = v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *GetCollectionSamplesMetadataParams) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCollectionSamplesMetadataParams) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *GetCollectionSamplesMetadataParams) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *GetCollectionSamplesMetadataParams) SetVersionId(v string) {
	o.VersionId = &v
}

// GetCollectionId returns the CollectionId field value
func (o *GetCollectionSamplesMetadataParams) GetCollectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionId
}

// GetCollectionIdOk returns a tuple with the CollectionId field value
// and a boolean to check if the value has been set.
func (o *GetCollectionSamplesMetadataParams) GetCollectionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionId, true
}

// SetCollectionId sets field value
func (o *GetCollectionSamplesMetadataParams) SetCollectionId(v string) {
	o.CollectionId = v
}

// GetProjectId returns the ProjectId field value
func (o *GetCollectionSamplesMetadataParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GetCollectionSamplesMetadataParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GetCollectionSamplesMetadataParams) SetProjectId(v string) {
	o.ProjectId = v
}

func (o GetCollectionSamplesMetadataParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCollectionSamplesMetadataParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["inferenceArtifactId"] = o.InferenceArtifactId
	if !IsNil(o.VersionId) {
		toSerialize["versionId"] = o.VersionId
	}
	toSerialize["collectionId"] = o.CollectionId
	toSerialize["projectId"] = o.ProjectId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCollectionSamplesMetadataParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inferenceArtifactId",
		"collectionId",
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCollectionSamplesMetadataParams := _GetCollectionSamplesMetadataParams{}

	err = json.Unmarshal(data, &varGetCollectionSamplesMetadataParams)

	if err != nil {
		return err
	}

	*o = GetCollectionSamplesMetadataParams(varGetCollectionSamplesMetadataParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filters")
		delete(additionalProperties, "inferenceArtifactId")
		delete(additionalProperties, "versionId")
		delete(additionalProperties, "collectionId")
		delete(additionalProperties, "projectId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCollectionSamplesMetadataParams struct {
	value *GetCollectionSamplesMetadataParams
	isSet bool
}

func (v NullableGetCollectionSamplesMetadataParams) Get() *GetCollectionSamplesMetadataParams {
	return v.value
}

func (v *NullableGetCollectionSamplesMetadataParams) Set(val *GetCollectionSamplesMetadataParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCollectionSamplesMetadataParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCollectionSamplesMetadataParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCollectionSamplesMetadataParams(val *GetCollectionSamplesMetadataParams) *NullableGetCollectionSamplesMetadataParams {
	return &NullableGetCollectionSamplesMetadataParams{value: val, isSet: true}
}

func (v NullableGetCollectionSamplesMetadataParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCollectionSamplesMetadataParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
