/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetVersionsVisualizationsParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVersionsVisualizationsParams{}

// GetVersionsVisualizationsParams struct for GetVersionsVisualizationsParams
type GetVersionsVisualizationsParams struct {
	VersionIds           []string `json:"versionIds"`
	ProjectId            string   `json:"projectId"`
	AdditionalProperties map[string]interface{}
}

type _GetVersionsVisualizationsParams GetVersionsVisualizationsParams

// NewGetVersionsVisualizationsParams instantiates a new GetVersionsVisualizationsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVersionsVisualizationsParams(versionIds []string, projectId string) *GetVersionsVisualizationsParams {
	this := GetVersionsVisualizationsParams{}
	this.VersionIds = versionIds
	this.ProjectId = projectId
	return &this
}

// NewGetVersionsVisualizationsParamsWithDefaults instantiates a new GetVersionsVisualizationsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVersionsVisualizationsParamsWithDefaults() *GetVersionsVisualizationsParams {
	this := GetVersionsVisualizationsParams{}
	return &this
}

// GetVersionIds returns the VersionIds field value
func (o *GetVersionsVisualizationsParams) GetVersionIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.VersionIds
}

// GetVersionIdsOk returns a tuple with the VersionIds field value
// and a boolean to check if the value has been set.
func (o *GetVersionsVisualizationsParams) GetVersionIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VersionIds, true
}

// SetVersionIds sets field value
func (o *GetVersionsVisualizationsParams) SetVersionIds(v []string) {
	o.VersionIds = v
}

// GetProjectId returns the ProjectId field value
func (o *GetVersionsVisualizationsParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GetVersionsVisualizationsParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GetVersionsVisualizationsParams) SetProjectId(v string) {
	o.ProjectId = v
}

func (o GetVersionsVisualizationsParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVersionsVisualizationsParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["versionIds"] = o.VersionIds
	toSerialize["projectId"] = o.ProjectId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetVersionsVisualizationsParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"versionIds",
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetVersionsVisualizationsParams := _GetVersionsVisualizationsParams{}

	err = json.Unmarshal(data, &varGetVersionsVisualizationsParams)

	if err != nil {
		return err
	}

	*o = GetVersionsVisualizationsParams(varGetVersionsVisualizationsParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "versionIds")
		delete(additionalProperties, "projectId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetVersionsVisualizationsParams struct {
	value *GetVersionsVisualizationsParams
	isSet bool
}

func (v NullableGetVersionsVisualizationsParams) Get() *GetVersionsVisualizationsParams {
	return v.value
}

func (v *NullableGetVersionsVisualizationsParams) Set(val *GetVersionsVisualizationsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVersionsVisualizationsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVersionsVisualizationsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVersionsVisualizationsParams(val *GetVersionsVisualizationsParams) *NullableGetVersionsVisualizationsParams {
	return &NullableGetVersionsVisualizationsParams{value: val, isSet: true}
}

func (v NullableGetVersionsVisualizationsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVersionsVisualizationsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
