/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.151
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ListAnalysisTargetsResponseMe type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAnalysisTargetsResponseMe{}

// ListAnalysisTargetsResponseMe struct for ListAnalysisTargetsResponseMe
type ListAnalysisTargetsResponseMe struct {
	Role                 string `json:"role"`
	TeamId               string `json:"teamId"`
	Name                 string `json:"name"`
	Email                string `json:"email"`
	AdditionalProperties map[string]interface{}
}

type _ListAnalysisTargetsResponseMe ListAnalysisTargetsResponseMe

// NewListAnalysisTargetsResponseMe instantiates a new ListAnalysisTargetsResponseMe object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAnalysisTargetsResponseMe(role string, teamId string, name string, email string) *ListAnalysisTargetsResponseMe {
	this := ListAnalysisTargetsResponseMe{}
	this.Role = role
	this.TeamId = teamId
	this.Name = name
	this.Email = email
	return &this
}

// NewListAnalysisTargetsResponseMeWithDefaults instantiates a new ListAnalysisTargetsResponseMe object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAnalysisTargetsResponseMeWithDefaults() *ListAnalysisTargetsResponseMe {
	this := ListAnalysisTargetsResponseMe{}
	return &this
}

// GetRole returns the Role field value
func (o *ListAnalysisTargetsResponseMe) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ListAnalysisTargetsResponseMe) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ListAnalysisTargetsResponseMe) SetRole(v string) {
	o.Role = v
}

// GetTeamId returns the TeamId field value
func (o *ListAnalysisTargetsResponseMe) GetTeamId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value
// and a boolean to check if the value has been set.
func (o *ListAnalysisTargetsResponseMe) GetTeamIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamId, true
}

// SetTeamId sets field value
func (o *ListAnalysisTargetsResponseMe) SetTeamId(v string) {
	o.TeamId = v
}

// GetName returns the Name field value
func (o *ListAnalysisTargetsResponseMe) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListAnalysisTargetsResponseMe) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListAnalysisTargetsResponseMe) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *ListAnalysisTargetsResponseMe) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ListAnalysisTargetsResponseMe) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ListAnalysisTargetsResponseMe) SetEmail(v string) {
	o.Email = v
}

func (o ListAnalysisTargetsResponseMe) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAnalysisTargetsResponseMe) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["teamId"] = o.TeamId
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAnalysisTargetsResponseMe) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
		"teamId",
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAnalysisTargetsResponseMe := _ListAnalysisTargetsResponseMe{}

	err = json.Unmarshal(data, &varListAnalysisTargetsResponseMe)

	if err != nil {
		return err
	}

	*o = ListAnalysisTargetsResponseMe(varListAnalysisTargetsResponseMe)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "role")
		delete(additionalProperties, "teamId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "email")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAnalysisTargetsResponseMe struct {
	value *ListAnalysisTargetsResponseMe
	isSet bool
}

func (v NullableListAnalysisTargetsResponseMe) Get() *ListAnalysisTargetsResponseMe {
	return v.value
}

func (v *NullableListAnalysisTargetsResponseMe) Set(val *ListAnalysisTargetsResponseMe) {
	v.value = val
	v.isSet = true
}

func (v NullableListAnalysisTargetsResponseMe) IsSet() bool {
	return v.isSet
}

func (v *NullableListAnalysisTargetsResponseMe) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAnalysisTargetsResponseMe(val *ListAnalysisTargetsResponseMe) *NullableListAnalysisTargetsResponseMe {
	return &NullableListAnalysisTargetsResponseMe{value: val, isSet: true}
}

func (v NullableListAnalysisTargetsResponseMe) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAnalysisTargetsResponseMe) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
