/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.360
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
)

// checks if the TrashSecretManagerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrashSecretManagerResponse{}

// TrashSecretManagerResponse struct for TrashSecretManagerResponse
type TrashSecretManagerResponse struct {
	Success bool `json:"success"`
}

// NewTrashSecretManagerResponse instantiates a new TrashSecretManagerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrashSecretManagerResponse(success bool) *TrashSecretManagerResponse {
	this := TrashSecretManagerResponse{}
	this.Success = success
	return &this
}

// NewTrashSecretManagerResponseWithDefaults instantiates a new TrashSecretManagerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrashSecretManagerResponseWithDefaults() *TrashSecretManagerResponse {
	this := TrashSecretManagerResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *TrashSecretManagerResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *TrashSecretManagerResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *TrashSecretManagerResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o TrashSecretManagerResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrashSecretManagerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

type NullableTrashSecretManagerResponse struct {
	value *TrashSecretManagerResponse
	isSet bool
}

func (v NullableTrashSecretManagerResponse) Get() *TrashSecretManagerResponse {
	return v.value
}

func (v *NullableTrashSecretManagerResponse) Set(val *TrashSecretManagerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTrashSecretManagerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTrashSecretManagerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrashSecretManagerResponse(val *TrashSecretManagerResponse) *NullableTrashSecretManagerResponse {
	return &NullableTrashSecretManagerResponse{value: val, isSet: true}
}

func (v NullableTrashSecretManagerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrashSecretManagerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


