/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetExportedModelJobsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetExportedModelJobsResponse{}

// GetExportedModelJobsResponse struct for GetExportedModelJobsResponse
type GetExportedModelJobsResponse struct {
	ExportedModelData    []ExportedModelData `json:"exportedModelData"`
	AdditionalProperties map[string]interface{}
}

type _GetExportedModelJobsResponse GetExportedModelJobsResponse

// NewGetExportedModelJobsResponse instantiates a new GetExportedModelJobsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExportedModelJobsResponse(exportedModelData []ExportedModelData) *GetExportedModelJobsResponse {
	this := GetExportedModelJobsResponse{}
	this.ExportedModelData = exportedModelData
	return &this
}

// NewGetExportedModelJobsResponseWithDefaults instantiates a new GetExportedModelJobsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExportedModelJobsResponseWithDefaults() *GetExportedModelJobsResponse {
	this := GetExportedModelJobsResponse{}
	return &this
}

// GetExportedModelData returns the ExportedModelData field value
func (o *GetExportedModelJobsResponse) GetExportedModelData() []ExportedModelData {
	if o == nil {
		var ret []ExportedModelData
		return ret
	}

	return o.ExportedModelData
}

// GetExportedModelDataOk returns a tuple with the ExportedModelData field value
// and a boolean to check if the value has been set.
func (o *GetExportedModelJobsResponse) GetExportedModelDataOk() ([]ExportedModelData, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExportedModelData, true
}

// SetExportedModelData sets field value
func (o *GetExportedModelJobsResponse) SetExportedModelData(v []ExportedModelData) {
	o.ExportedModelData = v
}

func (o GetExportedModelJobsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetExportedModelJobsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["exportedModelData"] = o.ExportedModelData

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetExportedModelJobsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"exportedModelData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetExportedModelJobsResponse := _GetExportedModelJobsResponse{}

	err = json.Unmarshal(data, &varGetExportedModelJobsResponse)

	if err != nil {
		return err
	}

	*o = GetExportedModelJobsResponse(varGetExportedModelJobsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "exportedModelData")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetExportedModelJobsResponse struct {
	value *GetExportedModelJobsResponse
	isSet bool
}

func (v NullableGetExportedModelJobsResponse) Get() *GetExportedModelJobsResponse {
	return v.value
}

func (v *NullableGetExportedModelJobsResponse) Set(val *GetExportedModelJobsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExportedModelJobsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExportedModelJobsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExportedModelJobsResponse(val *GetExportedModelJobsResponse) *NullableGetExportedModelJobsResponse {
	return &NullableGetExportedModelJobsResponse{value: val, isSet: true}
}

func (v NullableGetExportedModelJobsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExportedModelJobsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
