/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.29
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetExportedModelJobsParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetExportedModelJobsParams{}

// GetExportedModelJobsParams struct for GetExportedModelJobsParams
type GetExportedModelJobsParams struct {
	VersionId            string `json:"versionId"`
	ProjectId            string `json:"projectId"`
	AdditionalProperties map[string]interface{}
}

type _GetExportedModelJobsParams GetExportedModelJobsParams

// NewGetExportedModelJobsParams instantiates a new GetExportedModelJobsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExportedModelJobsParams(versionId string, projectId string) *GetExportedModelJobsParams {
	this := GetExportedModelJobsParams{}
	this.VersionId = versionId
	this.ProjectId = projectId
	return &this
}

// NewGetExportedModelJobsParamsWithDefaults instantiates a new GetExportedModelJobsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExportedModelJobsParamsWithDefaults() *GetExportedModelJobsParams {
	this := GetExportedModelJobsParams{}
	return &this
}

// GetVersionId returns the VersionId field value
func (o *GetExportedModelJobsParams) GetVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value
// and a boolean to check if the value has been set.
func (o *GetExportedModelJobsParams) GetVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionId, true
}

// SetVersionId sets field value
func (o *GetExportedModelJobsParams) SetVersionId(v string) {
	o.VersionId = v
}

// GetProjectId returns the ProjectId field value
func (o *GetExportedModelJobsParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GetExportedModelJobsParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GetExportedModelJobsParams) SetProjectId(v string) {
	o.ProjectId = v
}

func (o GetExportedModelJobsParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetExportedModelJobsParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["versionId"] = o.VersionId
	toSerialize["projectId"] = o.ProjectId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetExportedModelJobsParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"versionId",
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetExportedModelJobsParams := _GetExportedModelJobsParams{}

	err = json.Unmarshal(data, &varGetExportedModelJobsParams)

	if err != nil {
		return err
	}

	*o = GetExportedModelJobsParams(varGetExportedModelJobsParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "versionId")
		delete(additionalProperties, "projectId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetExportedModelJobsParams struct {
	value *GetExportedModelJobsParams
	isSet bool
}

func (v NullableGetExportedModelJobsParams) Get() *GetExportedModelJobsParams {
	return v.value
}

func (v *NullableGetExportedModelJobsParams) Set(val *GetExportedModelJobsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExportedModelJobsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExportedModelJobsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExportedModelJobsParams(val *GetExportedModelJobsParams) *NullableGetExportedModelJobsParams {
	return &NullableGetExportedModelJobsParams{value: val, isSet: true}
}

func (v NullableGetExportedModelJobsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExportedModelJobsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
