/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.151
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetAnalysisSampleAssetsParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAnalysisSampleAssetsParams{}

// GetAnalysisSampleAssetsParams struct for GetAnalysisSampleAssetsParams
type GetAnalysisSampleAssetsParams struct {
	ProjectId            string   `json:"projectId"`
	VersionId            string   `json:"versionId"`
	SampleIds            []string `json:"sampleIds"`
	Origin               *string  `json:"origin,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAnalysisSampleAssetsParams GetAnalysisSampleAssetsParams

// NewGetAnalysisSampleAssetsParams instantiates a new GetAnalysisSampleAssetsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnalysisSampleAssetsParams(projectId string, versionId string, sampleIds []string) *GetAnalysisSampleAssetsParams {
	this := GetAnalysisSampleAssetsParams{}
	this.ProjectId = projectId
	this.VersionId = versionId
	this.SampleIds = sampleIds
	return &this
}

// NewGetAnalysisSampleAssetsParamsWithDefaults instantiates a new GetAnalysisSampleAssetsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnalysisSampleAssetsParamsWithDefaults() *GetAnalysisSampleAssetsParams {
	this := GetAnalysisSampleAssetsParams{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *GetAnalysisSampleAssetsParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GetAnalysisSampleAssetsParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GetAnalysisSampleAssetsParams) SetProjectId(v string) {
	o.ProjectId = v
}

// GetVersionId returns the VersionId field value
func (o *GetAnalysisSampleAssetsParams) GetVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value
// and a boolean to check if the value has been set.
func (o *GetAnalysisSampleAssetsParams) GetVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionId, true
}

// SetVersionId sets field value
func (o *GetAnalysisSampleAssetsParams) SetVersionId(v string) {
	o.VersionId = v
}

// GetSampleIds returns the SampleIds field value
func (o *GetAnalysisSampleAssetsParams) GetSampleIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SampleIds
}

// GetSampleIdsOk returns a tuple with the SampleIds field value
// and a boolean to check if the value has been set.
func (o *GetAnalysisSampleAssetsParams) GetSampleIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SampleIds, true
}

// SetSampleIds sets field value
func (o *GetAnalysisSampleAssetsParams) SetSampleIds(v []string) {
	o.SampleIds = v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *GetAnalysisSampleAssetsParams) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAnalysisSampleAssetsParams) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *GetAnalysisSampleAssetsParams) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *GetAnalysisSampleAssetsParams) SetOrigin(v string) {
	o.Origin = &v
}

func (o GetAnalysisSampleAssetsParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAnalysisSampleAssetsParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	toSerialize["versionId"] = o.VersionId
	toSerialize["sampleIds"] = o.SampleIds
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAnalysisSampleAssetsParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectId",
		"versionId",
		"sampleIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAnalysisSampleAssetsParams := _GetAnalysisSampleAssetsParams{}

	err = json.Unmarshal(data, &varGetAnalysisSampleAssetsParams)

	if err != nil {
		return err
	}

	*o = GetAnalysisSampleAssetsParams(varGetAnalysisSampleAssetsParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "projectId")
		delete(additionalProperties, "versionId")
		delete(additionalProperties, "sampleIds")
		delete(additionalProperties, "origin")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAnalysisSampleAssetsParams struct {
	value *GetAnalysisSampleAssetsParams
	isSet bool
}

func (v NullableGetAnalysisSampleAssetsParams) Get() *GetAnalysisSampleAssetsParams {
	return v.value
}

func (v *NullableGetAnalysisSampleAssetsParams) Set(val *GetAnalysisSampleAssetsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnalysisSampleAssetsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnalysisSampleAssetsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnalysisSampleAssetsParams(val *GetAnalysisSampleAssetsParams) *NullableGetAnalysisSampleAssetsParams {
	return &NullableGetAnalysisSampleAssetsParams{value: val, isSet: true}
}

func (v NullableGetAnalysisSampleAssetsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnalysisSampleAssetsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
