/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.151
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the UnlabeledAnalysis type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnlabeledAnalysis{}

// UnlabeledAnalysis struct for UnlabeledAnalysis
type UnlabeledAnalysis struct {
	Id                   string      `json:"id"`
	JobId                string      `json:"jobId"`
	VersionId            string      `json:"versionId"`
	VersionName          string      `json:"versionName"`
	CreatedAt            time.Time   `json:"createdAt"`
	CreatedBy            string      `json:"createdBy"`
	StatsFileUrl         *string     `json:"statsFileUrl,omitempty"`
	Status               JobStatus   `json:"status"`
	IsDeleted            bool        `json:"isDeleted"`
	Filters              []ESFilter  `json:"filters,omitempty"`
	LatentSpaceType      *string     `json:"latentSpaceType,omitempty"`
	RunProcess           *RunProcess `json:"runProcess,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UnlabeledAnalysis UnlabeledAnalysis

// NewUnlabeledAnalysis instantiates a new UnlabeledAnalysis object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnlabeledAnalysis(id string, jobId string, versionId string, versionName string, createdAt time.Time, createdBy string, status JobStatus, isDeleted bool) *UnlabeledAnalysis {
	this := UnlabeledAnalysis{}
	this.Id = id
	this.JobId = jobId
	this.VersionId = versionId
	this.VersionName = versionName
	this.CreatedAt = createdAt
	this.CreatedBy = createdBy
	this.Status = status
	this.IsDeleted = isDeleted
	return &this
}

// NewUnlabeledAnalysisWithDefaults instantiates a new UnlabeledAnalysis object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnlabeledAnalysisWithDefaults() *UnlabeledAnalysis {
	this := UnlabeledAnalysis{}
	return &this
}

// GetId returns the Id field value
func (o *UnlabeledAnalysis) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UnlabeledAnalysis) SetId(v string) {
	o.Id = v
}

// GetJobId returns the JobId field value
func (o *UnlabeledAnalysis) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *UnlabeledAnalysis) SetJobId(v string) {
	o.JobId = v
}

// GetVersionId returns the VersionId field value
func (o *UnlabeledAnalysis) GetVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionId, true
}

// SetVersionId sets field value
func (o *UnlabeledAnalysis) SetVersionId(v string) {
	o.VersionId = v
}

// GetVersionName returns the VersionName field value
func (o *UnlabeledAnalysis) GetVersionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionName
}

// GetVersionNameOk returns a tuple with the VersionName field value
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetVersionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionName, true
}

// SetVersionName sets field value
func (o *UnlabeledAnalysis) SetVersionName(v string) {
	o.VersionName = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UnlabeledAnalysis) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UnlabeledAnalysis) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *UnlabeledAnalysis) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *UnlabeledAnalysis) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetStatsFileUrl returns the StatsFileUrl field value if set, zero value otherwise.
func (o *UnlabeledAnalysis) GetStatsFileUrl() string {
	if o == nil || IsNil(o.StatsFileUrl) {
		var ret string
		return ret
	}
	return *o.StatsFileUrl
}

// GetStatsFileUrlOk returns a tuple with the StatsFileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetStatsFileUrlOk() (*string, bool) {
	if o == nil || IsNil(o.StatsFileUrl) {
		return nil, false
	}
	return o.StatsFileUrl, true
}

// HasStatsFileUrl returns a boolean if a field has been set.
func (o *UnlabeledAnalysis) HasStatsFileUrl() bool {
	if o != nil && !IsNil(o.StatsFileUrl) {
		return true
	}

	return false
}

// SetStatsFileUrl gets a reference to the given string and assigns it to the StatsFileUrl field.
func (o *UnlabeledAnalysis) SetStatsFileUrl(v string) {
	o.StatsFileUrl = &v
}

// GetStatus returns the Status field value
func (o *UnlabeledAnalysis) GetStatus() JobStatus {
	if o == nil {
		var ret JobStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetStatusOk() (*JobStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UnlabeledAnalysis) SetStatus(v JobStatus) {
	o.Status = v
}

// GetIsDeleted returns the IsDeleted field value
func (o *UnlabeledAnalysis) GetIsDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetIsDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDeleted, true
}

// SetIsDeleted sets field value
func (o *UnlabeledAnalysis) SetIsDeleted(v bool) {
	o.IsDeleted = v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *UnlabeledAnalysis) GetFilters() []ESFilter {
	if o == nil || IsNil(o.Filters) {
		var ret []ESFilter
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetFiltersOk() ([]ESFilter, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *UnlabeledAnalysis) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []ESFilter and assigns it to the Filters field.
func (o *UnlabeledAnalysis) SetFilters(v []ESFilter) {
	o.Filters = v
}

// GetLatentSpaceType returns the LatentSpaceType field value if set, zero value otherwise.
func (o *UnlabeledAnalysis) GetLatentSpaceType() string {
	if o == nil || IsNil(o.LatentSpaceType) {
		var ret string
		return ret
	}
	return *o.LatentSpaceType
}

// GetLatentSpaceTypeOk returns a tuple with the LatentSpaceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetLatentSpaceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.LatentSpaceType) {
		return nil, false
	}
	return o.LatentSpaceType, true
}

// HasLatentSpaceType returns a boolean if a field has been set.
func (o *UnlabeledAnalysis) HasLatentSpaceType() bool {
	if o != nil && !IsNil(o.LatentSpaceType) {
		return true
	}

	return false
}

// SetLatentSpaceType gets a reference to the given string and assigns it to the LatentSpaceType field.
func (o *UnlabeledAnalysis) SetLatentSpaceType(v string) {
	o.LatentSpaceType = &v
}

// GetRunProcess returns the RunProcess field value if set, zero value otherwise.
func (o *UnlabeledAnalysis) GetRunProcess() RunProcess {
	if o == nil || IsNil(o.RunProcess) {
		var ret RunProcess
		return ret
	}
	return *o.RunProcess
}

// GetRunProcessOk returns a tuple with the RunProcess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnlabeledAnalysis) GetRunProcessOk() (*RunProcess, bool) {
	if o == nil || IsNil(o.RunProcess) {
		return nil, false
	}
	return o.RunProcess, true
}

// HasRunProcess returns a boolean if a field has been set.
func (o *UnlabeledAnalysis) HasRunProcess() bool {
	if o != nil && !IsNil(o.RunProcess) {
		return true
	}

	return false
}

// SetRunProcess gets a reference to the given RunProcess and assigns it to the RunProcess field.
func (o *UnlabeledAnalysis) SetRunProcess(v RunProcess) {
	o.RunProcess = &v
}

func (o UnlabeledAnalysis) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnlabeledAnalysis) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["jobId"] = o.JobId
	toSerialize["versionId"] = o.VersionId
	toSerialize["versionName"] = o.VersionName
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["createdBy"] = o.CreatedBy
	if !IsNil(o.StatsFileUrl) {
		toSerialize["statsFileUrl"] = o.StatsFileUrl
	}
	toSerialize["status"] = o.Status
	toSerialize["isDeleted"] = o.IsDeleted
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.LatentSpaceType) {
		toSerialize["latentSpaceType"] = o.LatentSpaceType
	}
	if !IsNil(o.RunProcess) {
		toSerialize["runProcess"] = o.RunProcess
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UnlabeledAnalysis) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"jobId",
		"versionId",
		"versionName",
		"createdAt",
		"createdBy",
		"status",
		"isDeleted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnlabeledAnalysis := _UnlabeledAnalysis{}

	err = json.Unmarshal(data, &varUnlabeledAnalysis)

	if err != nil {
		return err
	}

	*o = UnlabeledAnalysis(varUnlabeledAnalysis)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "jobId")
		delete(additionalProperties, "versionId")
		delete(additionalProperties, "versionName")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "createdBy")
		delete(additionalProperties, "statsFileUrl")
		delete(additionalProperties, "status")
		delete(additionalProperties, "isDeleted")
		delete(additionalProperties, "filters")
		delete(additionalProperties, "latentSpaceType")
		delete(additionalProperties, "runProcess")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUnlabeledAnalysis struct {
	value *UnlabeledAnalysis
	isSet bool
}

func (v NullableUnlabeledAnalysis) Get() *UnlabeledAnalysis {
	return v.value
}

func (v *NullableUnlabeledAnalysis) Set(val *UnlabeledAnalysis) {
	v.value = val
	v.isSet = true
}

func (v NullableUnlabeledAnalysis) IsSet() bool {
	return v.isSet
}

func (v *NullableUnlabeledAnalysis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnlabeledAnalysis(val *UnlabeledAnalysis) *NullableUnlabeledAnalysis {
	return &NullableUnlabeledAnalysis{value: val, isSet: true}
}

func (v NullableUnlabeledAnalysis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnlabeledAnalysis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
