/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.668
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ApproveInsightsParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveInsightsParams{}

// ApproveInsightsParams struct for ApproveInsightsParams
type ApproveInsightsParams struct {
	PopExpDigest         string    `json:"popExpDigest"`
	InsightIndexes       []float64 `json:"insightIndexes"`
	ProjectId            string    `json:"projectId"`
	AdditionalProperties map[string]interface{}
}

type _ApproveInsightsParams ApproveInsightsParams

// NewApproveInsightsParams instantiates a new ApproveInsightsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveInsightsParams(popExpDigest string, insightIndexes []float64, projectId string) *ApproveInsightsParams {
	this := ApproveInsightsParams{}
	this.PopExpDigest = popExpDigest
	this.InsightIndexes = insightIndexes
	this.ProjectId = projectId
	return &this
}

// NewApproveInsightsParamsWithDefaults instantiates a new ApproveInsightsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveInsightsParamsWithDefaults() *ApproveInsightsParams {
	this := ApproveInsightsParams{}
	return &this
}

// GetPopExpDigest returns the PopExpDigest field value
func (o *ApproveInsightsParams) GetPopExpDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PopExpDigest
}

// GetPopExpDigestOk returns a tuple with the PopExpDigest field value
// and a boolean to check if the value has been set.
func (o *ApproveInsightsParams) GetPopExpDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PopExpDigest, true
}

// SetPopExpDigest sets field value
func (o *ApproveInsightsParams) SetPopExpDigest(v string) {
	o.PopExpDigest = v
}

// GetInsightIndexes returns the InsightIndexes field value
func (o *ApproveInsightsParams) GetInsightIndexes() []float64 {
	if o == nil {
		var ret []float64
		return ret
	}

	return o.InsightIndexes
}

// GetInsightIndexesOk returns a tuple with the InsightIndexes field value
// and a boolean to check if the value has been set.
func (o *ApproveInsightsParams) GetInsightIndexesOk() ([]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.InsightIndexes, true
}

// SetInsightIndexes sets field value
func (o *ApproveInsightsParams) SetInsightIndexes(v []float64) {
	o.InsightIndexes = v
}

// GetProjectId returns the ProjectId field value
func (o *ApproveInsightsParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ApproveInsightsParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ApproveInsightsParams) SetProjectId(v string) {
	o.ProjectId = v
}

func (o ApproveInsightsParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveInsightsParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["popExpDigest"] = o.PopExpDigest
	toSerialize["insightIndexes"] = o.InsightIndexes
	toSerialize["projectId"] = o.ProjectId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApproveInsightsParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"popExpDigest",
		"insightIndexes",
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproveInsightsParams := _ApproveInsightsParams{}

	err = json.Unmarshal(data, &varApproveInsightsParams)

	if err != nil {
		return err
	}

	*o = ApproveInsightsParams(varApproveInsightsParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "popExpDigest")
		delete(additionalProperties, "insightIndexes")
		delete(additionalProperties, "projectId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApproveInsightsParams struct {
	value *ApproveInsightsParams
	isSet bool
}

func (v NullableApproveInsightsParams) Get() *ApproveInsightsParams {
	return v.value
}

func (v *NullableApproveInsightsParams) Set(val *ApproveInsightsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveInsightsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveInsightsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveInsightsParams(val *ApproveInsightsParams) *NullableApproveInsightsParams {
	return &NullableApproveInsightsParams{value: val, isSet: true}
}

func (v NullableApproveInsightsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveInsightsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
