/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.172
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
)

// checks if the GetAiAccessParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAiAccessParams{}

// GetAiAccessParams struct for GetAiAccessParams
type GetAiAccessParams struct {
	ProjectId            *string `json:"projectId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAiAccessParams GetAiAccessParams

// NewGetAiAccessParams instantiates a new GetAiAccessParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAiAccessParams() *GetAiAccessParams {
	this := GetAiAccessParams{}
	return &this
}

// NewGetAiAccessParamsWithDefaults instantiates a new GetAiAccessParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAiAccessParamsWithDefaults() *GetAiAccessParams {
	this := GetAiAccessParams{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GetAiAccessParams) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAiAccessParams) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GetAiAccessParams) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *GetAiAccessParams) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o GetAiAccessParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAiAccessParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAiAccessParams) UnmarshalJSON(data []byte) (err error) {
	varGetAiAccessParams := _GetAiAccessParams{}

	err = json.Unmarshal(data, &varGetAiAccessParams)

	if err != nil {
		return err
	}

	*o = GetAiAccessParams(varGetAiAccessParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "projectId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAiAccessParams struct {
	value *GetAiAccessParams
	isSet bool
}

func (v NullableGetAiAccessParams) Get() *GetAiAccessParams {
	return v.value
}

func (v *NullableGetAiAccessParams) Set(val *GetAiAccessParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAiAccessParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAiAccessParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAiAccessParams(val *GetAiAccessParams) *NullableGetAiAccessParams {
	return &NullableGetAiAccessParams{value: val, isSet: true}
}

func (v NullableGetAiAccessParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAiAccessParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
