/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.682
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the EpochMetricsValueAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EpochMetricsValueAnyOf1{}

// EpochMetricsValueAnyOf1 struct for EpochMetricsValueAnyOf1
type EpochMetricsValueAnyOf1 struct {
	Value                float64 `json:"value"`
	Type                 string  `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _EpochMetricsValueAnyOf1 EpochMetricsValueAnyOf1

// NewEpochMetricsValueAnyOf1 instantiates a new EpochMetricsValueAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEpochMetricsValueAnyOf1(value float64, type_ string) *EpochMetricsValueAnyOf1 {
	this := EpochMetricsValueAnyOf1{}
	this.Value = value
	this.Type = type_
	return &this
}

// NewEpochMetricsValueAnyOf1WithDefaults instantiates a new EpochMetricsValueAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEpochMetricsValueAnyOf1WithDefaults() *EpochMetricsValueAnyOf1 {
	this := EpochMetricsValueAnyOf1{}
	return &this
}

// GetValue returns the Value field value
func (o *EpochMetricsValueAnyOf1) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *EpochMetricsValueAnyOf1) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *EpochMetricsValueAnyOf1) SetValue(v float64) {
	o.Value = v
}

// GetType returns the Type field value
func (o *EpochMetricsValueAnyOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EpochMetricsValueAnyOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EpochMetricsValueAnyOf1) SetType(v string) {
	o.Type = v
}

func (o EpochMetricsValueAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EpochMetricsValueAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EpochMetricsValueAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEpochMetricsValueAnyOf1 := _EpochMetricsValueAnyOf1{}

	err = json.Unmarshal(data, &varEpochMetricsValueAnyOf1)

	if err != nil {
		return err
	}

	*o = EpochMetricsValueAnyOf1(varEpochMetricsValueAnyOf1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEpochMetricsValueAnyOf1 struct {
	value *EpochMetricsValueAnyOf1
	isSet bool
}

func (v NullableEpochMetricsValueAnyOf1) Get() *EpochMetricsValueAnyOf1 {
	return v.value
}

func (v *NullableEpochMetricsValueAnyOf1) Set(val *EpochMetricsValueAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableEpochMetricsValueAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableEpochMetricsValueAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEpochMetricsValueAnyOf1(val *EpochMetricsValueAnyOf1) *NullableEpochMetricsValueAnyOf1 {
	return &NullableEpochMetricsValueAnyOf1{value: val, isSet: true}
}

func (v NullableEpochMetricsValueAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEpochMetricsValueAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
