/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.683
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GenerateInsightsParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateInsightsParams{}

// GenerateInsightsParams struct for GenerateInsightsParams
type GenerateInsightsParams struct {
	ProjectId            string     `json:"projectId"`
	SessionRunId         string     `json:"sessionRunId"`
	Filters              []ESFilter `json:"filters,omitempty"`
	Refresh              *bool      `json:"refresh,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GenerateInsightsParams GenerateInsightsParams

// NewGenerateInsightsParams instantiates a new GenerateInsightsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateInsightsParams(projectId string, sessionRunId string) *GenerateInsightsParams {
	this := GenerateInsightsParams{}
	this.ProjectId = projectId
	this.SessionRunId = sessionRunId
	return &this
}

// NewGenerateInsightsParamsWithDefaults instantiates a new GenerateInsightsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateInsightsParamsWithDefaults() *GenerateInsightsParams {
	this := GenerateInsightsParams{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *GenerateInsightsParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GenerateInsightsParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GenerateInsightsParams) SetProjectId(v string) {
	o.ProjectId = v
}

// GetSessionRunId returns the SessionRunId field value
func (o *GenerateInsightsParams) GetSessionRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionRunId
}

// GetSessionRunIdOk returns a tuple with the SessionRunId field value
// and a boolean to check if the value has been set.
func (o *GenerateInsightsParams) GetSessionRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionRunId, true
}

// SetSessionRunId sets field value
func (o *GenerateInsightsParams) SetSessionRunId(v string) {
	o.SessionRunId = v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *GenerateInsightsParams) GetFilters() []ESFilter {
	if o == nil || IsNil(o.Filters) {
		var ret []ESFilter
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateInsightsParams) GetFiltersOk() ([]ESFilter, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *GenerateInsightsParams) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []ESFilter and assigns it to the Filters field.
func (o *GenerateInsightsParams) SetFilters(v []ESFilter) {
	o.Filters = v
}

// GetRefresh returns the Refresh field value if set, zero value otherwise.
func (o *GenerateInsightsParams) GetRefresh() bool {
	if o == nil || IsNil(o.Refresh) {
		var ret bool
		return ret
	}
	return *o.Refresh
}

// GetRefreshOk returns a tuple with the Refresh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateInsightsParams) GetRefreshOk() (*bool, bool) {
	if o == nil || IsNil(o.Refresh) {
		return nil, false
	}
	return o.Refresh, true
}

// HasRefresh returns a boolean if a field has been set.
func (o *GenerateInsightsParams) HasRefresh() bool {
	if o != nil && !IsNil(o.Refresh) {
		return true
	}

	return false
}

// SetRefresh gets a reference to the given bool and assigns it to the Refresh field.
func (o *GenerateInsightsParams) SetRefresh(v bool) {
	o.Refresh = &v
}

func (o GenerateInsightsParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateInsightsParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	toSerialize["sessionRunId"] = o.SessionRunId
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.Refresh) {
		toSerialize["refresh"] = o.Refresh
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GenerateInsightsParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectId",
		"sessionRunId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenerateInsightsParams := _GenerateInsightsParams{}

	err = json.Unmarshal(data, &varGenerateInsightsParams)

	if err != nil {
		return err
	}

	*o = GenerateInsightsParams(varGenerateInsightsParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "projectId")
		delete(additionalProperties, "sessionRunId")
		delete(additionalProperties, "filters")
		delete(additionalProperties, "refresh")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGenerateInsightsParams struct {
	value *GenerateInsightsParams
	isSet bool
}

func (v NullableGenerateInsightsParams) Get() *GenerateInsightsParams {
	return v.value
}

func (v *NullableGenerateInsightsParams) Set(val *GenerateInsightsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateInsightsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateInsightsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateInsightsParams(val *GenerateInsightsParams) *NullableGenerateInsightsParams {
	return &NullableGenerateInsightsParams{value: val, isSet: true}
}

func (v NullableGenerateInsightsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateInsightsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
