/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.682
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the InsightsJobParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InsightsJobParams{}

// InsightsJobParams struct for InsightsJobParams
type InsightsJobParams struct {
	Filters              []ESFilter `json:"filters,omitempty"`
	SessionRunId         string     `json:"sessionRunId"`
	Type                 string     `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _InsightsJobParams InsightsJobParams

// NewInsightsJobParams instantiates a new InsightsJobParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsightsJobParams(sessionRunId string, type_ string) *InsightsJobParams {
	this := InsightsJobParams{}
	this.SessionRunId = sessionRunId
	this.Type = type_
	return &this
}

// NewInsightsJobParamsWithDefaults instantiates a new InsightsJobParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsightsJobParamsWithDefaults() *InsightsJobParams {
	this := InsightsJobParams{}
	return &this
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *InsightsJobParams) GetFilters() []ESFilter {
	if o == nil || IsNil(o.Filters) {
		var ret []ESFilter
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightsJobParams) GetFiltersOk() ([]ESFilter, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *InsightsJobParams) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []ESFilter and assigns it to the Filters field.
func (o *InsightsJobParams) SetFilters(v []ESFilter) {
	o.Filters = v
}

// GetSessionRunId returns the SessionRunId field value
func (o *InsightsJobParams) GetSessionRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionRunId
}

// GetSessionRunIdOk returns a tuple with the SessionRunId field value
// and a boolean to check if the value has been set.
func (o *InsightsJobParams) GetSessionRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionRunId, true
}

// SetSessionRunId sets field value
func (o *InsightsJobParams) SetSessionRunId(v string) {
	o.SessionRunId = v
}

// GetType returns the Type field value
func (o *InsightsJobParams) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InsightsJobParams) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InsightsJobParams) SetType(v string) {
	o.Type = v
}

func (o InsightsJobParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InsightsJobParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["sessionRunId"] = o.SessionRunId
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InsightsJobParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessionRunId",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInsightsJobParams := _InsightsJobParams{}

	err = json.Unmarshal(data, &varInsightsJobParams)

	if err != nil {
		return err
	}

	*o = InsightsJobParams(varInsightsJobParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filters")
		delete(additionalProperties, "sessionRunId")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInsightsJobParams struct {
	value *InsightsJobParams
	isSet bool
}

func (v NullableInsightsJobParams) Get() *InsightsJobParams {
	return v.value
}

func (v *NullableInsightsJobParams) Set(val *InsightsJobParams) {
	v.value = val
	v.isSet = true
}

func (v NullableInsightsJobParams) IsSet() bool {
	return v.isSet
}

func (v *NullableInsightsJobParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsightsJobParams(val *InsightsJobParams) *NullableInsightsJobParams {
	return &NullableInsightsJobParams{value: val, isSet: true}
}

func (v NullableInsightsJobParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsightsJobParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
