/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.659
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DeleteGeneratedLabelParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteGeneratedLabelParams{}

// DeleteGeneratedLabelParams struct for DeleteGeneratedLabelParams
type DeleteGeneratedLabelParams struct {
	ProjectId            string `json:"projectId"`
	LabelId              string `json:"labelId"`
	AdditionalProperties map[string]interface{}
}

type _DeleteGeneratedLabelParams DeleteGeneratedLabelParams

// NewDeleteGeneratedLabelParams instantiates a new DeleteGeneratedLabelParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteGeneratedLabelParams(projectId string, labelId string) *DeleteGeneratedLabelParams {
	this := DeleteGeneratedLabelParams{}
	this.ProjectId = projectId
	this.LabelId = labelId
	return &this
}

// NewDeleteGeneratedLabelParamsWithDefaults instantiates a new DeleteGeneratedLabelParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteGeneratedLabelParamsWithDefaults() *DeleteGeneratedLabelParams {
	this := DeleteGeneratedLabelParams{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *DeleteGeneratedLabelParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *DeleteGeneratedLabelParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *DeleteGeneratedLabelParams) SetProjectId(v string) {
	o.ProjectId = v
}

// GetLabelId returns the LabelId field value
func (o *DeleteGeneratedLabelParams) GetLabelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LabelId
}

// GetLabelIdOk returns a tuple with the LabelId field value
// and a boolean to check if the value has been set.
func (o *DeleteGeneratedLabelParams) GetLabelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LabelId, true
}

// SetLabelId sets field value
func (o *DeleteGeneratedLabelParams) SetLabelId(v string) {
	o.LabelId = v
}

func (o DeleteGeneratedLabelParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteGeneratedLabelParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	toSerialize["labelId"] = o.LabelId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeleteGeneratedLabelParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectId",
		"labelId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteGeneratedLabelParams := _DeleteGeneratedLabelParams{}

	err = json.Unmarshal(data, &varDeleteGeneratedLabelParams)

	if err != nil {
		return err
	}

	*o = DeleteGeneratedLabelParams(varDeleteGeneratedLabelParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "projectId")
		delete(additionalProperties, "labelId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteGeneratedLabelParams struct {
	value *DeleteGeneratedLabelParams
	isSet bool
}

func (v NullableDeleteGeneratedLabelParams) Get() *DeleteGeneratedLabelParams {
	return v.value
}

func (v *NullableDeleteGeneratedLabelParams) Set(val *DeleteGeneratedLabelParams) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteGeneratedLabelParams) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteGeneratedLabelParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteGeneratedLabelParams(val *DeleteGeneratedLabelParams) *NullableDeleteGeneratedLabelParams {
	return &NullableDeleteGeneratedLabelParams{value: val, isSet: true}
}

func (v NullableDeleteGeneratedLabelParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteGeneratedLabelParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
