/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.646
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
)

// checks if the CalcPopulationExplorationDigestParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalcPopulationExplorationDigestParams{}

// CalcPopulationExplorationDigestParams struct for CalcPopulationExplorationDigestParams
type CalcPopulationExplorationDigestParams struct {
	PopulationParams PickPopulationExplorationParamsExcludeKeyofPopulationExplorationParamsDigestOrProjectIdOrReRunAfterFail `json:"populationParams"`
}

// NewCalcPopulationExplorationDigestParams instantiates a new CalcPopulationExplorationDigestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalcPopulationExplorationDigestParams(populationParams PickPopulationExplorationParamsExcludeKeyofPopulationExplorationParamsDigestOrProjectIdOrReRunAfterFail) *CalcPopulationExplorationDigestParams {
	this := CalcPopulationExplorationDigestParams{}
	this.PopulationParams = populationParams
	return &this
}

// NewCalcPopulationExplorationDigestParamsWithDefaults instantiates a new CalcPopulationExplorationDigestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalcPopulationExplorationDigestParamsWithDefaults() *CalcPopulationExplorationDigestParams {
	this := CalcPopulationExplorationDigestParams{}
	return &this
}

// GetPopulationParams returns the PopulationParams field value
func (o *CalcPopulationExplorationDigestParams) GetPopulationParams() PickPopulationExplorationParamsExcludeKeyofPopulationExplorationParamsDigestOrProjectIdOrReRunAfterFail {
	if o == nil {
		var ret PickPopulationExplorationParamsExcludeKeyofPopulationExplorationParamsDigestOrProjectIdOrReRunAfterFail
		return ret
	}

	return o.PopulationParams
}

// GetPopulationParamsOk returns a tuple with the PopulationParams field value
// and a boolean to check if the value has been set.
func (o *CalcPopulationExplorationDigestParams) GetPopulationParamsOk() (*PickPopulationExplorationParamsExcludeKeyofPopulationExplorationParamsDigestOrProjectIdOrReRunAfterFail, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PopulationParams, true
}

// SetPopulationParams sets field value
func (o *CalcPopulationExplorationDigestParams) SetPopulationParams(v PickPopulationExplorationParamsExcludeKeyofPopulationExplorationParamsDigestOrProjectIdOrReRunAfterFail) {
	o.PopulationParams = v
}

func (o CalcPopulationExplorationDigestParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalcPopulationExplorationDigestParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["populationParams"] = o.PopulationParams
	return toSerialize, nil
}

type NullableCalcPopulationExplorationDigestParams struct {
	value *CalcPopulationExplorationDigestParams
	isSet bool
}

func (v NullableCalcPopulationExplorationDigestParams) Get() *CalcPopulationExplorationDigestParams {
	return v.value
}

func (v *NullableCalcPopulationExplorationDigestParams) Set(val *CalcPopulationExplorationDigestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableCalcPopulationExplorationDigestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableCalcPopulationExplorationDigestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalcPopulationExplorationDigestParams(val *CalcPopulationExplorationDigestParams) *NullableCalcPopulationExplorationDigestParams {
	return &NullableCalcPopulationExplorationDigestParams{value: val, isSet: true}
}

func (v NullableCalcPopulationExplorationDigestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalcPopulationExplorationDigestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
