/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.20-rc.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the EpochData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EpochData{}

// EpochData struct for EpochData
type EpochData struct {
	VersionId             string                 `json:"versionId"`
	Epoch                 float64                `json:"epoch"`
	Tags                  []string               `json:"tags"`
	UploadedModelFilePath *string                `json:"uploadedModelFilePath,omitempty"`
	ExternalData          *EpochDataExternalData `json:"externalData,omitempty"`
	AdditionalProperties  map[string]interface{}
}

type _EpochData EpochData

// NewEpochData instantiates a new EpochData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEpochData(versionId string, epoch float64, tags []string) *EpochData {
	this := EpochData{}
	this.VersionId = versionId
	this.Epoch = epoch
	this.Tags = tags
	return &this
}

// NewEpochDataWithDefaults instantiates a new EpochData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEpochDataWithDefaults() *EpochData {
	this := EpochData{}
	return &this
}

// GetVersionId returns the VersionId field value
func (o *EpochData) GetVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value
// and a boolean to check if the value has been set.
func (o *EpochData) GetVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionId, true
}

// SetVersionId sets field value
func (o *EpochData) SetVersionId(v string) {
	o.VersionId = v
}

// GetEpoch returns the Epoch field value
func (o *EpochData) GetEpoch() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Epoch
}

// GetEpochOk returns a tuple with the Epoch field value
// and a boolean to check if the value has been set.
func (o *EpochData) GetEpochOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Epoch, true
}

// SetEpoch sets field value
func (o *EpochData) SetEpoch(v float64) {
	o.Epoch = v
}

// GetTags returns the Tags field value
func (o *EpochData) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *EpochData) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *EpochData) SetTags(v []string) {
	o.Tags = v
}

// GetUploadedModelFilePath returns the UploadedModelFilePath field value if set, zero value otherwise.
func (o *EpochData) GetUploadedModelFilePath() string {
	if o == nil || IsNil(o.UploadedModelFilePath) {
		var ret string
		return ret
	}
	return *o.UploadedModelFilePath
}

// GetUploadedModelFilePathOk returns a tuple with the UploadedModelFilePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EpochData) GetUploadedModelFilePathOk() (*string, bool) {
	if o == nil || IsNil(o.UploadedModelFilePath) {
		return nil, false
	}
	return o.UploadedModelFilePath, true
}

// HasUploadedModelFilePath returns a boolean if a field has been set.
func (o *EpochData) HasUploadedModelFilePath() bool {
	if o != nil && !IsNil(o.UploadedModelFilePath) {
		return true
	}

	return false
}

// SetUploadedModelFilePath gets a reference to the given string and assigns it to the UploadedModelFilePath field.
func (o *EpochData) SetUploadedModelFilePath(v string) {
	o.UploadedModelFilePath = &v
}

// GetExternalData returns the ExternalData field value if set, zero value otherwise.
func (o *EpochData) GetExternalData() EpochDataExternalData {
	if o == nil || IsNil(o.ExternalData) {
		var ret EpochDataExternalData
		return ret
	}
	return *o.ExternalData
}

// GetExternalDataOk returns a tuple with the ExternalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EpochData) GetExternalDataOk() (*EpochDataExternalData, bool) {
	if o == nil || IsNil(o.ExternalData) {
		return nil, false
	}
	return o.ExternalData, true
}

// HasExternalData returns a boolean if a field has been set.
func (o *EpochData) HasExternalData() bool {
	if o != nil && !IsNil(o.ExternalData) {
		return true
	}

	return false
}

// SetExternalData gets a reference to the given EpochDataExternalData and assigns it to the ExternalData field.
func (o *EpochData) SetExternalData(v EpochDataExternalData) {
	o.ExternalData = &v
}

func (o EpochData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EpochData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["versionId"] = o.VersionId
	toSerialize["epoch"] = o.Epoch
	toSerialize["tags"] = o.Tags
	if !IsNil(o.UploadedModelFilePath) {
		toSerialize["uploadedModelFilePath"] = o.UploadedModelFilePath
	}
	if !IsNil(o.ExternalData) {
		toSerialize["externalData"] = o.ExternalData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EpochData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"versionId",
		"epoch",
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEpochData := _EpochData{}

	err = json.Unmarshal(data, &varEpochData)

	if err != nil {
		return err
	}

	*o = EpochData(varEpochData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "versionId")
		delete(additionalProperties, "epoch")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "uploadedModelFilePath")
		delete(additionalProperties, "externalData")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEpochData struct {
	value *EpochData
	isSet bool
}

func (v NullableEpochData) Get() *EpochData {
	return v.value
}

func (v *NullableEpochData) Set(val *EpochData) {
	v.value = val
	v.isSet = true
}

func (v NullableEpochData) IsSet() bool {
	return v.isSet
}

func (v *NullableEpochData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEpochData(val *EpochData) *NullableEpochData {
	return &NullableEpochData{value: val, isSet: true}
}

func (v NullableEpochData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEpochData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
