/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.670
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the UnderRepresentationInsight type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnderRepresentationInsight{}

// UnderRepresentationInsight struct for UnderRepresentationInsight
type UnderRepresentationInsight struct {
	Type                         ScatterInsightType             `json:"type"`
	Filters                      []ScatterFilter                `json:"filters,omitempty"`
	NSamples                     float64                        `json:"n_samples"`
	MutualInfoElements           []MutualInformationElement     `json:"mutual_info_elements"`
	BlobPath                     string                         `json:"blob_path"`
	InsightSubCategoryDsCuration *InsightSubCategoryDSCuration  `json:"insight_sub_category_ds_curation,omitempty"`
	InsightCategoryPerformance   *InsightSubCategoryPerformance `json:"insight_category_performance,omitempty"`
	Severity                     float64                        `json:"severity"`
	SeverityMetrics              []SeverityMetricElement        `json:"severity_metrics"`
	MetricsInfo                  []InsightMetricInfo            `json:"metrics_info"`
	Index                        float64                        `json:"index"`
	MinHash                      []float64                      `json:"min_hash"`
	CsvPath                      *string                        `json:"csv_path,omitempty"`
	AutomaticTests               []InsightAutomaticTest         `json:"automatic_tests,omitempty"`
	UnderRepresentationDataset   DataStateType                  `json:"under_representation_dataset"`
	UnderRepresentationNSamples  float64                        `json:"under_representation_n_samples"`
	OverRepresentationDataset    DataStateType                  `json:"over_representation_dataset"`
	OverRepresentationNSamples   float64                        `json:"over_representation_n_samples"`
	AdditionalProperties         map[string]interface{}
}

type _UnderRepresentationInsight UnderRepresentationInsight

// NewUnderRepresentationInsight instantiates a new UnderRepresentationInsight object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnderRepresentationInsight(type_ ScatterInsightType, nSamples float64, mutualInfoElements []MutualInformationElement, blobPath string, severity float64, severityMetrics []SeverityMetricElement, metricsInfo []InsightMetricInfo, index float64, minHash []float64, underRepresentationDataset DataStateType, underRepresentationNSamples float64, overRepresentationDataset DataStateType, overRepresentationNSamples float64) *UnderRepresentationInsight {
	this := UnderRepresentationInsight{}
	this.Type = type_
	this.NSamples = nSamples
	this.MutualInfoElements = mutualInfoElements
	this.BlobPath = blobPath
	this.Severity = severity
	this.SeverityMetrics = severityMetrics
	this.MetricsInfo = metricsInfo
	this.Index = index
	this.MinHash = minHash
	this.UnderRepresentationDataset = underRepresentationDataset
	this.UnderRepresentationNSamples = underRepresentationNSamples
	this.OverRepresentationDataset = overRepresentationDataset
	this.OverRepresentationNSamples = overRepresentationNSamples
	return &this
}

// NewUnderRepresentationInsightWithDefaults instantiates a new UnderRepresentationInsight object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnderRepresentationInsightWithDefaults() *UnderRepresentationInsight {
	this := UnderRepresentationInsight{}
	return &this
}

// GetType returns the Type field value
func (o *UnderRepresentationInsight) GetType() ScatterInsightType {
	if o == nil {
		var ret ScatterInsightType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetTypeOk() (*ScatterInsightType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UnderRepresentationInsight) SetType(v ScatterInsightType) {
	o.Type = v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *UnderRepresentationInsight) GetFilters() []ScatterFilter {
	if o == nil || IsNil(o.Filters) {
		var ret []ScatterFilter
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetFiltersOk() ([]ScatterFilter, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *UnderRepresentationInsight) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []ScatterFilter and assigns it to the Filters field.
func (o *UnderRepresentationInsight) SetFilters(v []ScatterFilter) {
	o.Filters = v
}

// GetNSamples returns the NSamples field value
func (o *UnderRepresentationInsight) GetNSamples() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.NSamples
}

// GetNSamplesOk returns a tuple with the NSamples field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetNSamplesOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NSamples, true
}

// SetNSamples sets field value
func (o *UnderRepresentationInsight) SetNSamples(v float64) {
	o.NSamples = v
}

// GetMutualInfoElements returns the MutualInfoElements field value
func (o *UnderRepresentationInsight) GetMutualInfoElements() []MutualInformationElement {
	if o == nil {
		var ret []MutualInformationElement
		return ret
	}

	return o.MutualInfoElements
}

// GetMutualInfoElementsOk returns a tuple with the MutualInfoElements field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetMutualInfoElementsOk() ([]MutualInformationElement, bool) {
	if o == nil {
		return nil, false
	}
	return o.MutualInfoElements, true
}

// SetMutualInfoElements sets field value
func (o *UnderRepresentationInsight) SetMutualInfoElements(v []MutualInformationElement) {
	o.MutualInfoElements = v
}

// GetBlobPath returns the BlobPath field value
func (o *UnderRepresentationInsight) GetBlobPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlobPath
}

// GetBlobPathOk returns a tuple with the BlobPath field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetBlobPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlobPath, true
}

// SetBlobPath sets field value
func (o *UnderRepresentationInsight) SetBlobPath(v string) {
	o.BlobPath = v
}

// GetInsightSubCategoryDsCuration returns the InsightSubCategoryDsCuration field value if set, zero value otherwise.
func (o *UnderRepresentationInsight) GetInsightSubCategoryDsCuration() InsightSubCategoryDSCuration {
	if o == nil || IsNil(o.InsightSubCategoryDsCuration) {
		var ret InsightSubCategoryDSCuration
		return ret
	}
	return *o.InsightSubCategoryDsCuration
}

// GetInsightSubCategoryDsCurationOk returns a tuple with the InsightSubCategoryDsCuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetInsightSubCategoryDsCurationOk() (*InsightSubCategoryDSCuration, bool) {
	if o == nil || IsNil(o.InsightSubCategoryDsCuration) {
		return nil, false
	}
	return o.InsightSubCategoryDsCuration, true
}

// HasInsightSubCategoryDsCuration returns a boolean if a field has been set.
func (o *UnderRepresentationInsight) HasInsightSubCategoryDsCuration() bool {
	if o != nil && !IsNil(o.InsightSubCategoryDsCuration) {
		return true
	}

	return false
}

// SetInsightSubCategoryDsCuration gets a reference to the given InsightSubCategoryDSCuration and assigns it to the InsightSubCategoryDsCuration field.
func (o *UnderRepresentationInsight) SetInsightSubCategoryDsCuration(v InsightSubCategoryDSCuration) {
	o.InsightSubCategoryDsCuration = &v
}

// GetInsightCategoryPerformance returns the InsightCategoryPerformance field value if set, zero value otherwise.
func (o *UnderRepresentationInsight) GetInsightCategoryPerformance() InsightSubCategoryPerformance {
	if o == nil || IsNil(o.InsightCategoryPerformance) {
		var ret InsightSubCategoryPerformance
		return ret
	}
	return *o.InsightCategoryPerformance
}

// GetInsightCategoryPerformanceOk returns a tuple with the InsightCategoryPerformance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetInsightCategoryPerformanceOk() (*InsightSubCategoryPerformance, bool) {
	if o == nil || IsNil(o.InsightCategoryPerformance) {
		return nil, false
	}
	return o.InsightCategoryPerformance, true
}

// HasInsightCategoryPerformance returns a boolean if a field has been set.
func (o *UnderRepresentationInsight) HasInsightCategoryPerformance() bool {
	if o != nil && !IsNil(o.InsightCategoryPerformance) {
		return true
	}

	return false
}

// SetInsightCategoryPerformance gets a reference to the given InsightSubCategoryPerformance and assigns it to the InsightCategoryPerformance field.
func (o *UnderRepresentationInsight) SetInsightCategoryPerformance(v InsightSubCategoryPerformance) {
	o.InsightCategoryPerformance = &v
}

// GetSeverity returns the Severity field value
func (o *UnderRepresentationInsight) GetSeverity() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetSeverityOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *UnderRepresentationInsight) SetSeverity(v float64) {
	o.Severity = v
}

// GetSeverityMetrics returns the SeverityMetrics field value
func (o *UnderRepresentationInsight) GetSeverityMetrics() []SeverityMetricElement {
	if o == nil {
		var ret []SeverityMetricElement
		return ret
	}

	return o.SeverityMetrics
}

// GetSeverityMetricsOk returns a tuple with the SeverityMetrics field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetSeverityMetricsOk() ([]SeverityMetricElement, bool) {
	if o == nil {
		return nil, false
	}
	return o.SeverityMetrics, true
}

// SetSeverityMetrics sets field value
func (o *UnderRepresentationInsight) SetSeverityMetrics(v []SeverityMetricElement) {
	o.SeverityMetrics = v
}

// GetMetricsInfo returns the MetricsInfo field value
func (o *UnderRepresentationInsight) GetMetricsInfo() []InsightMetricInfo {
	if o == nil {
		var ret []InsightMetricInfo
		return ret
	}

	return o.MetricsInfo
}

// GetMetricsInfoOk returns a tuple with the MetricsInfo field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetMetricsInfoOk() ([]InsightMetricInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetricsInfo, true
}

// SetMetricsInfo sets field value
func (o *UnderRepresentationInsight) SetMetricsInfo(v []InsightMetricInfo) {
	o.MetricsInfo = v
}

// GetIndex returns the Index field value
func (o *UnderRepresentationInsight) GetIndex() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetIndexOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *UnderRepresentationInsight) SetIndex(v float64) {
	o.Index = v
}

// GetMinHash returns the MinHash field value
func (o *UnderRepresentationInsight) GetMinHash() []float64 {
	if o == nil {
		var ret []float64
		return ret
	}

	return o.MinHash
}

// GetMinHashOk returns a tuple with the MinHash field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetMinHashOk() ([]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinHash, true
}

// SetMinHash sets field value
func (o *UnderRepresentationInsight) SetMinHash(v []float64) {
	o.MinHash = v
}

// GetCsvPath returns the CsvPath field value if set, zero value otherwise.
func (o *UnderRepresentationInsight) GetCsvPath() string {
	if o == nil || IsNil(o.CsvPath) {
		var ret string
		return ret
	}
	return *o.CsvPath
}

// GetCsvPathOk returns a tuple with the CsvPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetCsvPathOk() (*string, bool) {
	if o == nil || IsNil(o.CsvPath) {
		return nil, false
	}
	return o.CsvPath, true
}

// HasCsvPath returns a boolean if a field has been set.
func (o *UnderRepresentationInsight) HasCsvPath() bool {
	if o != nil && !IsNil(o.CsvPath) {
		return true
	}

	return false
}

// SetCsvPath gets a reference to the given string and assigns it to the CsvPath field.
func (o *UnderRepresentationInsight) SetCsvPath(v string) {
	o.CsvPath = &v
}

// GetAutomaticTests returns the AutomaticTests field value if set, zero value otherwise.
func (o *UnderRepresentationInsight) GetAutomaticTests() []InsightAutomaticTest {
	if o == nil || IsNil(o.AutomaticTests) {
		var ret []InsightAutomaticTest
		return ret
	}
	return o.AutomaticTests
}

// GetAutomaticTestsOk returns a tuple with the AutomaticTests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetAutomaticTestsOk() ([]InsightAutomaticTest, bool) {
	if o == nil || IsNil(o.AutomaticTests) {
		return nil, false
	}
	return o.AutomaticTests, true
}

// HasAutomaticTests returns a boolean if a field has been set.
func (o *UnderRepresentationInsight) HasAutomaticTests() bool {
	if o != nil && !IsNil(o.AutomaticTests) {
		return true
	}

	return false
}

// SetAutomaticTests gets a reference to the given []InsightAutomaticTest and assigns it to the AutomaticTests field.
func (o *UnderRepresentationInsight) SetAutomaticTests(v []InsightAutomaticTest) {
	o.AutomaticTests = v
}

// GetUnderRepresentationDataset returns the UnderRepresentationDataset field value
func (o *UnderRepresentationInsight) GetUnderRepresentationDataset() DataStateType {
	if o == nil {
		var ret DataStateType
		return ret
	}

	return o.UnderRepresentationDataset
}

// GetUnderRepresentationDatasetOk returns a tuple with the UnderRepresentationDataset field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetUnderRepresentationDatasetOk() (*DataStateType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderRepresentationDataset, true
}

// SetUnderRepresentationDataset sets field value
func (o *UnderRepresentationInsight) SetUnderRepresentationDataset(v DataStateType) {
	o.UnderRepresentationDataset = v
}

// GetUnderRepresentationNSamples returns the UnderRepresentationNSamples field value
func (o *UnderRepresentationInsight) GetUnderRepresentationNSamples() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.UnderRepresentationNSamples
}

// GetUnderRepresentationNSamplesOk returns a tuple with the UnderRepresentationNSamples field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetUnderRepresentationNSamplesOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderRepresentationNSamples, true
}

// SetUnderRepresentationNSamples sets field value
func (o *UnderRepresentationInsight) SetUnderRepresentationNSamples(v float64) {
	o.UnderRepresentationNSamples = v
}

// GetOverRepresentationDataset returns the OverRepresentationDataset field value
func (o *UnderRepresentationInsight) GetOverRepresentationDataset() DataStateType {
	if o == nil {
		var ret DataStateType
		return ret
	}

	return o.OverRepresentationDataset
}

// GetOverRepresentationDatasetOk returns a tuple with the OverRepresentationDataset field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetOverRepresentationDatasetOk() (*DataStateType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverRepresentationDataset, true
}

// SetOverRepresentationDataset sets field value
func (o *UnderRepresentationInsight) SetOverRepresentationDataset(v DataStateType) {
	o.OverRepresentationDataset = v
}

// GetOverRepresentationNSamples returns the OverRepresentationNSamples field value
func (o *UnderRepresentationInsight) GetOverRepresentationNSamples() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.OverRepresentationNSamples
}

// GetOverRepresentationNSamplesOk returns a tuple with the OverRepresentationNSamples field value
// and a boolean to check if the value has been set.
func (o *UnderRepresentationInsight) GetOverRepresentationNSamplesOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverRepresentationNSamples, true
}

// SetOverRepresentationNSamples sets field value
func (o *UnderRepresentationInsight) SetOverRepresentationNSamples(v float64) {
	o.OverRepresentationNSamples = v
}

func (o UnderRepresentationInsight) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnderRepresentationInsight) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["n_samples"] = o.NSamples
	toSerialize["mutual_info_elements"] = o.MutualInfoElements
	toSerialize["blob_path"] = o.BlobPath
	if !IsNil(o.InsightSubCategoryDsCuration) {
		toSerialize["insight_sub_category_ds_curation"] = o.InsightSubCategoryDsCuration
	}
	if !IsNil(o.InsightCategoryPerformance) {
		toSerialize["insight_category_performance"] = o.InsightCategoryPerformance
	}
	toSerialize["severity"] = o.Severity
	toSerialize["severity_metrics"] = o.SeverityMetrics
	toSerialize["metrics_info"] = o.MetricsInfo
	toSerialize["index"] = o.Index
	toSerialize["min_hash"] = o.MinHash
	if !IsNil(o.CsvPath) {
		toSerialize["csv_path"] = o.CsvPath
	}
	if !IsNil(o.AutomaticTests) {
		toSerialize["automatic_tests"] = o.AutomaticTests
	}
	toSerialize["under_representation_dataset"] = o.UnderRepresentationDataset
	toSerialize["under_representation_n_samples"] = o.UnderRepresentationNSamples
	toSerialize["over_representation_dataset"] = o.OverRepresentationDataset
	toSerialize["over_representation_n_samples"] = o.OverRepresentationNSamples

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UnderRepresentationInsight) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"n_samples",
		"mutual_info_elements",
		"blob_path",
		"severity",
		"severity_metrics",
		"metrics_info",
		"index",
		"min_hash",
		"under_representation_dataset",
		"under_representation_n_samples",
		"over_representation_dataset",
		"over_representation_n_samples",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnderRepresentationInsight := _UnderRepresentationInsight{}

	err = json.Unmarshal(data, &varUnderRepresentationInsight)

	if err != nil {
		return err
	}

	*o = UnderRepresentationInsight(varUnderRepresentationInsight)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "filters")
		delete(additionalProperties, "n_samples")
		delete(additionalProperties, "mutual_info_elements")
		delete(additionalProperties, "blob_path")
		delete(additionalProperties, "insight_sub_category_ds_curation")
		delete(additionalProperties, "insight_category_performance")
		delete(additionalProperties, "severity")
		delete(additionalProperties, "severity_metrics")
		delete(additionalProperties, "metrics_info")
		delete(additionalProperties, "index")
		delete(additionalProperties, "min_hash")
		delete(additionalProperties, "csv_path")
		delete(additionalProperties, "automatic_tests")
		delete(additionalProperties, "under_representation_dataset")
		delete(additionalProperties, "under_representation_n_samples")
		delete(additionalProperties, "over_representation_dataset")
		delete(additionalProperties, "over_representation_n_samples")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUnderRepresentationInsight struct {
	value *UnderRepresentationInsight
	isSet bool
}

func (v NullableUnderRepresentationInsight) Get() *UnderRepresentationInsight {
	return v.value
}

func (v *NullableUnderRepresentationInsight) Set(val *UnderRepresentationInsight) {
	v.value = val
	v.isSet = true
}

func (v NullableUnderRepresentationInsight) IsSet() bool {
	return v.isSet
}

func (v *NullableUnderRepresentationInsight) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnderRepresentationInsight(val *UnderRepresentationInsight) *NullableUnderRepresentationInsight {
	return &NullableUnderRepresentationInsight{value: val, isSet: true}
}

func (v NullableUnderRepresentationInsight) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnderRepresentationInsight) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
