/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.20-rc.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the GeneratedLabel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeneratedLabel{}

// GeneratedLabel struct for GeneratedLabel
type GeneratedLabel struct {
	Id                   string      `json:"id"`
	JobId                string      `json:"jobId"`
	VersionId            string      `json:"versionId"`
	VersionName          string      `json:"versionName"`
	NumOfSamples         *float64    `json:"numOfSamples,omitempty"`
	CreatedAt            time.Time   `json:"createdAt"`
	CreatedBy            string      `json:"createdBy"`
	FilePath             string      `json:"filePath"`
	FileUrl              *string     `json:"fileUrl,omitempty"`
	FilterFileUrl        *string     `json:"filterFileUrl,omitempty"`
	Status               JobStatus   `json:"status"`
	IsDeleted            bool        `json:"isDeleted"`
	Filters              []ESFilter  `json:"filters,omitempty"`
	RunProcess           *RunProcess `json:"runProcess,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GeneratedLabel GeneratedLabel

// NewGeneratedLabel instantiates a new GeneratedLabel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeneratedLabel(id string, jobId string, versionId string, versionName string, createdAt time.Time, createdBy string, filePath string, status JobStatus, isDeleted bool) *GeneratedLabel {
	this := GeneratedLabel{}
	this.Id = id
	this.JobId = jobId
	this.VersionId = versionId
	this.VersionName = versionName
	this.CreatedAt = createdAt
	this.CreatedBy = createdBy
	this.FilePath = filePath
	this.Status = status
	this.IsDeleted = isDeleted
	return &this
}

// NewGeneratedLabelWithDefaults instantiates a new GeneratedLabel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeneratedLabelWithDefaults() *GeneratedLabel {
	this := GeneratedLabel{}
	return &this
}

// GetId returns the Id field value
func (o *GeneratedLabel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GeneratedLabel) SetId(v string) {
	o.Id = v
}

// GetJobId returns the JobId field value
func (o *GeneratedLabel) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *GeneratedLabel) SetJobId(v string) {
	o.JobId = v
}

// GetVersionId returns the VersionId field value
func (o *GeneratedLabel) GetVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionId, true
}

// SetVersionId sets field value
func (o *GeneratedLabel) SetVersionId(v string) {
	o.VersionId = v
}

// GetVersionName returns the VersionName field value
func (o *GeneratedLabel) GetVersionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionName
}

// GetVersionNameOk returns a tuple with the VersionName field value
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetVersionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionName, true
}

// SetVersionName sets field value
func (o *GeneratedLabel) SetVersionName(v string) {
	o.VersionName = v
}

// GetNumOfSamples returns the NumOfSamples field value if set, zero value otherwise.
func (o *GeneratedLabel) GetNumOfSamples() float64 {
	if o == nil || IsNil(o.NumOfSamples) {
		var ret float64
		return ret
	}
	return *o.NumOfSamples
}

// GetNumOfSamplesOk returns a tuple with the NumOfSamples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetNumOfSamplesOk() (*float64, bool) {
	if o == nil || IsNil(o.NumOfSamples) {
		return nil, false
	}
	return o.NumOfSamples, true
}

// HasNumOfSamples returns a boolean if a field has been set.
func (o *GeneratedLabel) HasNumOfSamples() bool {
	if o != nil && !IsNil(o.NumOfSamples) {
		return true
	}

	return false
}

// SetNumOfSamples gets a reference to the given float64 and assigns it to the NumOfSamples field.
func (o *GeneratedLabel) SetNumOfSamples(v float64) {
	o.NumOfSamples = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GeneratedLabel) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GeneratedLabel) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *GeneratedLabel) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *GeneratedLabel) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetFilePath returns the FilePath field value
func (o *GeneratedLabel) GetFilePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilePath
}

// GetFilePathOk returns a tuple with the FilePath field value
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetFilePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilePath, true
}

// SetFilePath sets field value
func (o *GeneratedLabel) SetFilePath(v string) {
	o.FilePath = v
}

// GetFileUrl returns the FileUrl field value if set, zero value otherwise.
func (o *GeneratedLabel) GetFileUrl() string {
	if o == nil || IsNil(o.FileUrl) {
		var ret string
		return ret
	}
	return *o.FileUrl
}

// GetFileUrlOk returns a tuple with the FileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetFileUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FileUrl) {
		return nil, false
	}
	return o.FileUrl, true
}

// HasFileUrl returns a boolean if a field has been set.
func (o *GeneratedLabel) HasFileUrl() bool {
	if o != nil && !IsNil(o.FileUrl) {
		return true
	}

	return false
}

// SetFileUrl gets a reference to the given string and assigns it to the FileUrl field.
func (o *GeneratedLabel) SetFileUrl(v string) {
	o.FileUrl = &v
}

// GetFilterFileUrl returns the FilterFileUrl field value if set, zero value otherwise.
func (o *GeneratedLabel) GetFilterFileUrl() string {
	if o == nil || IsNil(o.FilterFileUrl) {
		var ret string
		return ret
	}
	return *o.FilterFileUrl
}

// GetFilterFileUrlOk returns a tuple with the FilterFileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetFilterFileUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FilterFileUrl) {
		return nil, false
	}
	return o.FilterFileUrl, true
}

// HasFilterFileUrl returns a boolean if a field has been set.
func (o *GeneratedLabel) HasFilterFileUrl() bool {
	if o != nil && !IsNil(o.FilterFileUrl) {
		return true
	}

	return false
}

// SetFilterFileUrl gets a reference to the given string and assigns it to the FilterFileUrl field.
func (o *GeneratedLabel) SetFilterFileUrl(v string) {
	o.FilterFileUrl = &v
}

// GetStatus returns the Status field value
func (o *GeneratedLabel) GetStatus() JobStatus {
	if o == nil {
		var ret JobStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetStatusOk() (*JobStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GeneratedLabel) SetStatus(v JobStatus) {
	o.Status = v
}

// GetIsDeleted returns the IsDeleted field value
func (o *GeneratedLabel) GetIsDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetIsDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDeleted, true
}

// SetIsDeleted sets field value
func (o *GeneratedLabel) SetIsDeleted(v bool) {
	o.IsDeleted = v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *GeneratedLabel) GetFilters() []ESFilter {
	if o == nil || IsNil(o.Filters) {
		var ret []ESFilter
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetFiltersOk() ([]ESFilter, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *GeneratedLabel) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []ESFilter and assigns it to the Filters field.
func (o *GeneratedLabel) SetFilters(v []ESFilter) {
	o.Filters = v
}

// GetRunProcess returns the RunProcess field value if set, zero value otherwise.
func (o *GeneratedLabel) GetRunProcess() RunProcess {
	if o == nil || IsNil(o.RunProcess) {
		var ret RunProcess
		return ret
	}
	return *o.RunProcess
}

// GetRunProcessOk returns a tuple with the RunProcess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedLabel) GetRunProcessOk() (*RunProcess, bool) {
	if o == nil || IsNil(o.RunProcess) {
		return nil, false
	}
	return o.RunProcess, true
}

// HasRunProcess returns a boolean if a field has been set.
func (o *GeneratedLabel) HasRunProcess() bool {
	if o != nil && !IsNil(o.RunProcess) {
		return true
	}

	return false
}

// SetRunProcess gets a reference to the given RunProcess and assigns it to the RunProcess field.
func (o *GeneratedLabel) SetRunProcess(v RunProcess) {
	o.RunProcess = &v
}

func (o GeneratedLabel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeneratedLabel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["jobId"] = o.JobId
	toSerialize["versionId"] = o.VersionId
	toSerialize["versionName"] = o.VersionName
	if !IsNil(o.NumOfSamples) {
		toSerialize["numOfSamples"] = o.NumOfSamples
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["createdBy"] = o.CreatedBy
	toSerialize["filePath"] = o.FilePath
	if !IsNil(o.FileUrl) {
		toSerialize["fileUrl"] = o.FileUrl
	}
	if !IsNil(o.FilterFileUrl) {
		toSerialize["filterFileUrl"] = o.FilterFileUrl
	}
	toSerialize["status"] = o.Status
	toSerialize["isDeleted"] = o.IsDeleted
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.RunProcess) {
		toSerialize["runProcess"] = o.RunProcess
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GeneratedLabel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"jobId",
		"versionId",
		"versionName",
		"createdAt",
		"createdBy",
		"filePath",
		"status",
		"isDeleted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeneratedLabel := _GeneratedLabel{}

	err = json.Unmarshal(data, &varGeneratedLabel)

	if err != nil {
		return err
	}

	*o = GeneratedLabel(varGeneratedLabel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "jobId")
		delete(additionalProperties, "versionId")
		delete(additionalProperties, "versionName")
		delete(additionalProperties, "numOfSamples")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "createdBy")
		delete(additionalProperties, "filePath")
		delete(additionalProperties, "fileUrl")
		delete(additionalProperties, "filterFileUrl")
		delete(additionalProperties, "status")
		delete(additionalProperties, "isDeleted")
		delete(additionalProperties, "filters")
		delete(additionalProperties, "runProcess")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGeneratedLabel struct {
	value *GeneratedLabel
	isSet bool
}

func (v NullableGeneratedLabel) Get() *GeneratedLabel {
	return v.value
}

func (v *NullableGeneratedLabel) Set(val *GeneratedLabel) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneratedLabel) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneratedLabel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneratedLabel(val *GeneratedLabel) *NullableGeneratedLabel {
	return &NullableGeneratedLabel{value: val, isSet: true}
}

func (v NullableGeneratedLabel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneratedLabel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
