/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.151
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
)

// checks if the ListAnalysisTargetsParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAnalysisTargetsParams{}

// ListAnalysisTargetsParams struct for ListAnalysisTargetsParams
type ListAnalysisTargetsParams struct {
	ProjectId            *string `json:"projectId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAnalysisTargetsParams ListAnalysisTargetsParams

// NewListAnalysisTargetsParams instantiates a new ListAnalysisTargetsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAnalysisTargetsParams() *ListAnalysisTargetsParams {
	this := ListAnalysisTargetsParams{}
	return &this
}

// NewListAnalysisTargetsParamsWithDefaults instantiates a new ListAnalysisTargetsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAnalysisTargetsParamsWithDefaults() *ListAnalysisTargetsParams {
	this := ListAnalysisTargetsParams{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ListAnalysisTargetsParams) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAnalysisTargetsParams) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ListAnalysisTargetsParams) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *ListAnalysisTargetsParams) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o ListAnalysisTargetsParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAnalysisTargetsParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAnalysisTargetsParams) UnmarshalJSON(data []byte) (err error) {
	varListAnalysisTargetsParams := _ListAnalysisTargetsParams{}

	err = json.Unmarshal(data, &varListAnalysisTargetsParams)

	if err != nil {
		return err
	}

	*o = ListAnalysisTargetsParams(varListAnalysisTargetsParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "projectId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAnalysisTargetsParams struct {
	value *ListAnalysisTargetsParams
	isSet bool
}

func (v NullableListAnalysisTargetsParams) Get() *ListAnalysisTargetsParams {
	return v.value
}

func (v *NullableListAnalysisTargetsParams) Set(val *ListAnalysisTargetsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableListAnalysisTargetsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableListAnalysisTargetsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAnalysisTargetsParams(val *ListAnalysisTargetsParams) *NullableListAnalysisTargetsParams {
	return &NullableListAnalysisTargetsParams{value: val, isSet: true}
}

func (v NullableListAnalysisTargetsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAnalysisTargetsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
