/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.91
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetCollectionSampleOrderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCollectionSampleOrderResponse{}

// GetCollectionSampleOrderResponse struct for GetCollectionSampleOrderResponse
type GetCollectionSampleOrderResponse struct {
	Cursor *string  `json:"cursor,omitempty"`
	Total  *float64 `json:"total,omitempty"`
	// Same rows as `samples`, but with metadata/metrics flattened in. The table-pagination hook uses these directly as DataGrid rows.
	Rows []CollectionSampleRow `json:"rows"`
	// Identities-only — kept for callers that just need state/index.
	Samples              []SampleIdentity      `json:"samples"`
	Status               CollectionIndexStatus `json:"status"`
	AdditionalProperties map[string]interface{}
}

type _GetCollectionSampleOrderResponse GetCollectionSampleOrderResponse

// NewGetCollectionSampleOrderResponse instantiates a new GetCollectionSampleOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCollectionSampleOrderResponse(rows []CollectionSampleRow, samples []SampleIdentity, status CollectionIndexStatus) *GetCollectionSampleOrderResponse {
	this := GetCollectionSampleOrderResponse{}
	this.Rows = rows
	this.Samples = samples
	this.Status = status
	return &this
}

// NewGetCollectionSampleOrderResponseWithDefaults instantiates a new GetCollectionSampleOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCollectionSampleOrderResponseWithDefaults() *GetCollectionSampleOrderResponse {
	this := GetCollectionSampleOrderResponse{}
	return &this
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *GetCollectionSampleOrderResponse) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCollectionSampleOrderResponse) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *GetCollectionSampleOrderResponse) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *GetCollectionSampleOrderResponse) SetCursor(v string) {
	o.Cursor = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetCollectionSampleOrderResponse) GetTotal() float64 {
	if o == nil || IsNil(o.Total) {
		var ret float64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCollectionSampleOrderResponse) GetTotalOk() (*float64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetCollectionSampleOrderResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float64 and assigns it to the Total field.
func (o *GetCollectionSampleOrderResponse) SetTotal(v float64) {
	o.Total = &v
}

// GetRows returns the Rows field value
func (o *GetCollectionSampleOrderResponse) GetRows() []CollectionSampleRow {
	if o == nil {
		var ret []CollectionSampleRow
		return ret
	}

	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value
// and a boolean to check if the value has been set.
func (o *GetCollectionSampleOrderResponse) GetRowsOk() ([]CollectionSampleRow, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rows, true
}

// SetRows sets field value
func (o *GetCollectionSampleOrderResponse) SetRows(v []CollectionSampleRow) {
	o.Rows = v
}

// GetSamples returns the Samples field value
func (o *GetCollectionSampleOrderResponse) GetSamples() []SampleIdentity {
	if o == nil {
		var ret []SampleIdentity
		return ret
	}

	return o.Samples
}

// GetSamplesOk returns a tuple with the Samples field value
// and a boolean to check if the value has been set.
func (o *GetCollectionSampleOrderResponse) GetSamplesOk() ([]SampleIdentity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Samples, true
}

// SetSamples sets field value
func (o *GetCollectionSampleOrderResponse) SetSamples(v []SampleIdentity) {
	o.Samples = v
}

// GetStatus returns the Status field value
func (o *GetCollectionSampleOrderResponse) GetStatus() CollectionIndexStatus {
	if o == nil {
		var ret CollectionIndexStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetCollectionSampleOrderResponse) GetStatusOk() (*CollectionIndexStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetCollectionSampleOrderResponse) SetStatus(v CollectionIndexStatus) {
	o.Status = v
}

func (o GetCollectionSampleOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCollectionSampleOrderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	toSerialize["rows"] = o.Rows
	toSerialize["samples"] = o.Samples
	toSerialize["status"] = o.Status

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCollectionSampleOrderResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rows",
		"samples",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCollectionSampleOrderResponse := _GetCollectionSampleOrderResponse{}

	err = json.Unmarshal(data, &varGetCollectionSampleOrderResponse)

	if err != nil {
		return err
	}

	*o = GetCollectionSampleOrderResponse(varGetCollectionSampleOrderResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cursor")
		delete(additionalProperties, "total")
		delete(additionalProperties, "rows")
		delete(additionalProperties, "samples")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCollectionSampleOrderResponse struct {
	value *GetCollectionSampleOrderResponse
	isSet bool
}

func (v NullableGetCollectionSampleOrderResponse) Get() *GetCollectionSampleOrderResponse {
	return v.value
}

func (v *NullableGetCollectionSampleOrderResponse) Set(val *GetCollectionSampleOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCollectionSampleOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCollectionSampleOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCollectionSampleOrderResponse(val *GetCollectionSampleOrderResponse) *NullableGetCollectionSampleOrderResponse {
	return &NullableGetCollectionSampleOrderResponse{value: val, isSet: true}
}

func (v NullableGetCollectionSampleOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCollectionSampleOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
