/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 11.0.101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
	"fmt"
)

// CodeMetadataType the model 'CodeMetadataType'
type CodeMetadataType string

// List of CodeMetadataType
const (
	CODEMETADATATYPE_FLOAT   CodeMetadataType = "float"
	CODEMETADATATYPE_STRING  CodeMetadataType = "string"
	CODEMETADATATYPE_INT     CodeMetadataType = "int"
	CODEMETADATATYPE_BOOLEAN CodeMetadataType = "boolean"
)

// All allowed values of CodeMetadataType enum
var AllowedCodeMetadataTypeEnumValues = []CodeMetadataType{
	"float",
	"string",
	"int",
	"boolean",
}

func (v *CodeMetadataType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CodeMetadataType(value)
	for _, existing := range AllowedCodeMetadataTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CodeMetadataType", value)
}

// NewCodeMetadataTypeFromValue returns a pointer to a valid CodeMetadataType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCodeMetadataTypeFromValue(v string) (*CodeMetadataType, error) {
	ev := CodeMetadataType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CodeMetadataType: valid values are %v", v, AllowedCodeMetadataTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CodeMetadataType) IsValid() bool {
	for _, existing := range AllowedCodeMetadataTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CodeMetadataType value
func (v CodeMetadataType) Ptr() *CodeMetadataType {
	return &v
}

type NullableCodeMetadataType struct {
	value *CodeMetadataType
	isSet bool
}

func (v NullableCodeMetadataType) Get() *CodeMetadataType {
	return v.value
}

func (v *NullableCodeMetadataType) Set(val *CodeMetadataType) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeMetadataType) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeMetadataType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeMetadataType(val *CodeMetadataType) *NullableCodeMetadataType {
	return &NullableCodeMetadataType{value: val, isSet: true}
}

func (v NullableCodeMetadataType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeMetadataType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
