/*
node-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.557
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tensorleapapi

import (
	"encoding/json"
)

// checks if the GetCurrentProjectVersionParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCurrentProjectVersionParams{}

// GetCurrentProjectVersionParams struct for GetCurrentProjectVersionParams
type GetCurrentProjectVersionParams struct {
	ProjectId string `json:"projectId"`
}

// NewGetCurrentProjectVersionParams instantiates a new GetCurrentProjectVersionParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCurrentProjectVersionParams(projectId string) *GetCurrentProjectVersionParams {
	this := GetCurrentProjectVersionParams{}
	this.ProjectId = projectId
	return &this
}

// NewGetCurrentProjectVersionParamsWithDefaults instantiates a new GetCurrentProjectVersionParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCurrentProjectVersionParamsWithDefaults() *GetCurrentProjectVersionParams {
	this := GetCurrentProjectVersionParams{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *GetCurrentProjectVersionParams) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GetCurrentProjectVersionParams) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GetCurrentProjectVersionParams) SetProjectId(v string) {
	o.ProjectId = v
}

func (o GetCurrentProjectVersionParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCurrentProjectVersionParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	return toSerialize, nil
}

type NullableGetCurrentProjectVersionParams struct {
	value *GetCurrentProjectVersionParams
	isSet bool
}

func (v NullableGetCurrentProjectVersionParams) Get() *GetCurrentProjectVersionParams {
	return v.value
}

func (v *NullableGetCurrentProjectVersionParams) Set(val *GetCurrentProjectVersionParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCurrentProjectVersionParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCurrentProjectVersionParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCurrentProjectVersionParams(val *GetCurrentProjectVersionParams) *NullableGetCurrentProjectVersionParams {
	return &NullableGetCurrentProjectVersionParams{value: val, isSet: true}
}

func (v NullableGetCurrentProjectVersionParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCurrentProjectVersionParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
