name: CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Check format
        run: make check-fmt

      - name: Build
        run: go build .

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          only-new-issues: true

      - name: Test
        run: make test







  lint-install-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

